openapi: 3.0.3
info:
  title: FlashMind API
  version: 0.1.0
  description: |
    FlashMind API 契約

    ## 設計規範
    - Response 格式：統一 Wrapper `{ data, meta? }`
    - Error 格式：`{ error: { code, message } }`
    - 認證方式：HttpOnly Cookie
    - 詳見 ADR-016

servers:
  - url: https://api.flashmind.local

paths:
  # ============================================================
  # Auth
  # ============================================================
  /auth/register:
    post:
      operationId: register
      tags:
        - Auth
      summary: 註冊帳號
      description: 使用 Email 註冊新帳號，成功後設定 session cookie。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: 註冊成功
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
                example: session=abc123; HttpOnly; Secure; SameSite=Strict; Path=/
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: 輸入資料不完整或格式錯誤
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error:
                  code: VALIDATION_ERROR
                  message: 密碼至少需要 8 個字元
        "409":
          description: Email 已被使用
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error:
                  code: AUTH_EMAIL_ALREADY_EXISTS
                  message: 此 Email 已被註冊

  /auth/login:
    post:
      operationId: login
      tags:
        - Auth
      summary: 登入帳號
      description: 使用 Email + 密碼登入，成功後設定 session cookie。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: 登入成功
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          description: 輸入資料不完整或格式錯誤
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: 帳密錯誤
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error:
                  code: AUTH_INVALID_CREDENTIALS
                  message: Email 或密碼錯誤

  /auth/logout:
    post:
      operationId: logout
      tags:
        - Auth
      summary: 登出帳號
      description: 撤銷目前 session 並清除 cookie。
      security:
        - cookieAuth: []
      responses:
        "204":
          description: 登出成功
          headers:
            Set-Cookie:
              description: 清除 session cookie
              schema:
                type: string
                example: session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0
        "401":
          description: 未授權
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error:
                  code: UNAUTHORIZED
                  message: 請先登入

  /auth/google:
    get:
      operationId: initiateGoogleOAuth
      tags:
        - Auth
      summary: 發起 Google OAuth
      description: 重新導向至 Google 授權頁面。
      parameters:
        - name: rememberMe
          in: query
          description: 是否記住登入狀態
          schema:
            type: boolean
            default: false
      responses:
        "302":
          description: 重新導向至 Google 授權頁面
          headers:
            Location:
              description: Google OAuth 授權 URL
              schema:
                type: string

  /auth/google/callback:
    get:
      operationId: handleGoogleOAuthCallback
      tags:
        - Auth
      summary: Google OAuth Callback
      description: Google 授權完成後的回呼端點，驗證後設定 session cookie 並導向前端。
      parameters:
        - name: code
          in: query
          required: true
          description: Google 授權碼
          schema:
            type: string
        - name: state
          in: query
          description: 狀態參數（含 rememberMe 等資訊）
          schema:
            type: string
      responses:
        "302":
          description: 登入成功，導向前端主頁
          headers:
            Location:
              description: 前端主頁 URL
              schema:
                type: string
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
        "401":
          description: Google 授權失敗
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error:
                  code: AUTH_GOOGLE_FAILED
                  message: Google 登入失敗，請重試

  /auth/me:
    get:
      operationId: getCurrentUser
      tags:
        - Auth
      summary: 取得目前使用者資訊
      description: 取得目前登入使用者的資訊。
      security:
        - cookieAuth: []
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "401":
          description: 未授權
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error:
                  code: UNAUTHORIZED
                  message: 請先登入

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
      description: HttpOnly session cookie

  schemas:
    # ============================================================
    # Common
    # ============================================================
    ErrorResponse:
      type: object
      description: 錯誤回應（符合 ADR-016）
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              description: 機器可讀的錯誤碼（SCREAMING_SNAKE_CASE）
              example: AUTH_INVALID_CREDENTIALS
            message:
              type: string
              description: 使用者可讀的錯誤訊息
              example: Email 或密碼錯誤

    PaginationMeta:
      type: object
      description: 分頁資訊（cursor-based）
      properties:
        nextCursor:
          type: string
          nullable: true
          description: 下一頁的 cursor，若無更多資料則為 null
        hasMore:
          type: boolean
          description: 是否還有更多資料

    # ============================================================
    # Auth
    # ============================================================
    RegisterRequest:
      type: object
      description: Email 註冊請求
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
          description: 密碼（至少 8 字元）
          example: securepassword123

    LoginRequest:
      type: object
      description: Email 登入請求
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
          example: securepassword123
        rememberMe:
          type: boolean
          default: false
          description: 記住我（延長 session 效期至 30 天）

    User:
      type: object
      description: 使用者資料
      required:
        - id
        - email
        - primaryProvider
        - createdAt
      properties:
        id:
          type: string
          description: 使用者 ID（cuid）
          example: clh1234567890abcdef
        email:
          type: string
          format: email
          example: user@example.com
        primaryProvider:
          type: string
          enum: [email, google]
          description: 主要登入方式
        createdAt:
          type: string
          format: date-time
          description: 建立時間（ISO 8601 UTC）
          example: "2026-01-17T10:30:00Z"
        lastLoginAt:
          type: string
          format: date-time
          nullable: true
          description: 最後登入時間
          example: "2026-01-17T14:45:30Z"

    UserResponse:
      type: object
      description: 使用者回應（符合 ADR-016 統一 Wrapper）
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/User"
