// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type ServerSentEventsResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AddTargetVocabularyToDeckData,
  AddTargetVocabularyToDeckErrors,
  AddTargetVocabularyToDeckResponses,
  AppendSpeakingMessagesData,
  AppendSpeakingMessagesErrors,
  AppendSpeakingMessagesResponses,
  ApproveCliLoginAuthorizationData,
  ApproveCliLoginAuthorizationErrors,
  ApproveCliLoginAuthorizationResponses,
  ChatSpeakingAssistantData,
  ChatSpeakingAssistantErrors,
  ChatSpeakingAssistantResponses,
  CreateCardData,
  CreateCardErrors,
  CreateCardResponses,
  CreateCliLoginAuthorizationData,
  CreateCliLoginAuthorizationErrors,
  CreateCliLoginAuthorizationResponses,
  CreateCollectionChatMessageData,
  CreateCollectionChatMessageErrors,
  CreateCollectionChatMessageResponses,
  CreateCollectionChatSessionData,
  CreateCollectionChatSessionErrors,
  CreateCollectionChatSessionResponses,
  CreateCollectionItemData,
  CreateCollectionItemErrors,
  CreateCollectionItemResponses,
  CreateDeckData,
  CreateDeckErrors,
  CreateDeckResponses,
  CreateSpeakingAudioReplyData,
  CreateSpeakingAudioReplyErrors,
  CreateSpeakingAudioReplyResponses,
  CreateSpeakingReplyData,
  CreateSpeakingReplyErrors,
  CreateSpeakingReplyResponses,
  CreateSpeakingSessionData,
  CreateSpeakingSessionErrors,
  CreateSpeakingSessionResponses,
  CreateTopicConversationData,
  CreateTopicConversationDraftData,
  CreateTopicConversationDraftErrors,
  CreateTopicConversationDraftHintData,
  CreateTopicConversationDraftHintErrors,
  CreateTopicConversationDraftHintResponses,
  CreateTopicConversationDraftResponses,
  CreateTopicConversationErrors,
  CreateTopicConversationHintData,
  CreateTopicConversationHintErrors,
  CreateTopicConversationHintResponses,
  CreateTopicConversationMessageData,
  CreateTopicConversationMessageErrors,
  CreateTopicConversationMessageResponses,
  CreateTopicConversationResponses,
  DeleteCardData,
  DeleteCardErrors,
  DeleteCardResponses,
  DeleteCollectionItemData,
  DeleteCollectionItemErrors,
  DeleteCollectionItemResponses,
  DeleteDeckData,
  DeleteDeckErrors,
  DeleteDeckResponses,
  DeleteSpeakingSessionData,
  DeleteSpeakingSessionErrors,
  DeleteSpeakingSessionResponses,
  DeleteTopicConversationData,
  DeleteTopicConversationErrors,
  DeleteTopicConversationResponses,
  ExchangeCliLoginAuthorizationData,
  ExchangeCliLoginAuthorizationErrors,
  ExchangeCliLoginAuthorizationResponses,
  ExportDeckData,
  ExportDeckErrors,
  ExportDeckResponses,
  GenerateCardContentData,
  GenerateCardContentErrors,
  GenerateCardContentResponses,
  GenerateRelatedExampleData,
  GenerateRelatedExampleErrors,
  GenerateRelatedExampleResponses,
  GetCardData,
  GetCardErrors,
  GetCardResponses,
  GetCollectionItemData,
  GetCollectionItemErrors,
  GetCollectionItemResponses,
  GetCurrentUserData,
  GetCurrentUserErrors,
  GetCurrentUserResponses,
  GetDeckData,
  GetDeckErrors,
  GetDeckResponses,
  GetSpeakingPracticeContextData,
  GetSpeakingPracticeContextErrors,
  GetSpeakingPracticeContextResponses,
  GetSpeakingSessionData,
  GetSpeakingSessionErrors,
  GetSpeakingSessionResponses,
  GetStudyCardsData,
  GetStudyCardsErrors,
  GetStudyCardsResponses,
  GetStudySummaryData,
  GetStudySummaryErrors,
  GetStudySummaryResponses,
  GetTopicConversationData,
  GetTopicConversationErrors,
  GetTopicConversationResponses,
  HandleGoogleOAuthCallbackData,
  HandleGoogleOAuthCallbackErrors,
  ImportCardsData,
  ImportCardsErrors,
  ImportCardsResponses,
  ImportDeckData,
  ImportDeckErrors,
  ImportDeckResponses,
  ImportTargetVocabularyData,
  ImportTargetVocabularyErrors,
  ImportTargetVocabularyResponses,
  InitiateGoogleOAuthData,
  ListCardsData,
  ListCardsErrors,
  ListCardsResponses,
  ListCollectionChatMessagesData,
  ListCollectionChatMessagesErrors,
  ListCollectionChatMessagesResponses,
  ListCollectionItemsData,
  ListCollectionItemsErrors,
  ListCollectionItemsResponses,
  ListDecksData,
  ListDecksErrors,
  ListDecksResponses,
  ListSpeakingMessagesData,
  ListSpeakingMessagesErrors,
  ListSpeakingMessagesResponses,
  ListSpeakingSessionsData,
  ListSpeakingSessionsErrors,
  ListSpeakingSessionsResponses,
  ListTargetVocabularyData,
  ListTargetVocabularyErrors,
  ListTargetVocabularyResponses,
  ListTopicConversationsData,
  ListTopicConversationsErrors,
  ListTopicConversationsResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  MigrateSpeakingHistoryData,
  MigrateSpeakingHistoryErrors,
  MigrateSpeakingHistoryResponses,
  PreviewSpeakingVoiceData,
  PreviewSpeakingVoiceErrors,
  PreviewSpeakingVoiceResponses,
  RegisterData,
  RegisterErrors,
  RegisterResponses,
  RejectTargetVocabularyUseData,
  RejectTargetVocabularyUseErrors,
  RejectTargetVocabularyUseResponses,
  ReplayTopicConversationData,
  ReplayTopicConversationErrors,
  ReplayTopicConversationResponses,
  SaveSpeakingReviewData,
  SaveSpeakingReviewErrors,
  SaveSpeakingReviewResponses,
  SetDailyOverrideData,
  SetDailyOverrideErrors,
  SetDailyOverrideResponses,
  StreamSpeakingAssistantData,
  StreamSpeakingAssistantErrors,
  StreamSpeakingAssistantResponse,
  StreamSpeakingAssistantResponses,
  StreamTopicConversationMessageData,
  StreamTopicConversationMessageErrors,
  StreamTopicConversationMessageResponse,
  StreamTopicConversationMessageResponses,
  SubmitReviewData,
  SubmitReviewErrors,
  SubmitReviewResponses,
  SummarizeSpeakingConversationData,
  SummarizeSpeakingConversationErrors,
  SummarizeSpeakingConversationResponses,
  SynthesizeSpeechData,
  SynthesizeSpeechErrors,
  SynthesizeSpeechResponses,
  SynthesizeWordData,
  SynthesizeWordErrors,
  SynthesizeWordResponses,
  TranslateSpeakingTextData,
  TranslateSpeakingTextErrors,
  TranslateSpeakingTextResponses,
  UpdateCardData,
  UpdateCardErrors,
  UpdateCardResponses,
  UpdateCollectionItemData,
  UpdateCollectionItemErrors,
  UpdateCollectionItemResponses,
  UpdateDeckData,
  UpdateDeckErrors,
  UpdateDeckResponses,
  ValidateSpeakingReviewData,
  ValidateSpeakingReviewErrors,
  ValidateSpeakingReviewResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * 依練習時間列出 App 與本機歷史
 */
export const listSpeakingSessions = <ThrowOnError extends boolean = false>(
  options?: Options<ListSpeakingSessionsData, ThrowOnError>,
): RequestResult<
  ListSpeakingSessionsResponses,
  ListSpeakingSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListSpeakingSessionsResponses,
    ListSpeakingSessionsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/sessions",
    ...options,
  });

/**
 * 建立 App 文字練習場次
 */
export const createSpeakingSession = <ThrowOnError extends boolean = false>(
  options: Options<CreateSpeakingSessionData, ThrowOnError>,
): RequestResult<
  CreateSpeakingSessionResponses,
  CreateSpeakingSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSpeakingSessionResponses,
    CreateSpeakingSessionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 刪除歷史但不回退學習狀態
 */
export const deleteSpeakingSession = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSpeakingSessionData, ThrowOnError>,
): RequestResult<
  DeleteSpeakingSessionResponses,
  DeleteSpeakingSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteSpeakingSessionResponses,
    DeleteSpeakingSessionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/sessions/{id}",
    ...options,
  });

/**
 * 取得自己的場次與已保存 Review
 */
export const getSpeakingSession = <ThrowOnError extends boolean = false>(
  options: Options<GetSpeakingSessionData, ThrowOnError>,
): RequestResult<
  GetSpeakingSessionResponses,
  GetSpeakingSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSpeakingSessionResponses,
    GetSpeakingSessionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/sessions/{id}",
    ...options,
  });

/**
 * 依原始順序取得文字訊息
 */
export const listSpeakingMessages = <ThrowOnError extends boolean = false>(
  options: Options<ListSpeakingMessagesData, ThrowOnError>,
): RequestResult<
  ListSpeakingMessagesResponses,
  ListSpeakingMessagesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListSpeakingMessagesResponses,
    ListSpeakingMessagesErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/sessions/{id}/messages",
    ...options,
  });

/**
 * 保存最終文字，重送不重複
 */
export const appendSpeakingMessages = <ThrowOnError extends boolean = false>(
  options: Options<AppendSpeakingMessagesData, ThrowOnError>,
): RequestResult<
  AppendSpeakingMessagesResponses,
  AppendSpeakingMessagesErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AppendSpeakingMessagesResponses,
    AppendSpeakingMessagesErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/sessions/{id}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取得完整且唯讀的學習上下文
 */
export const getSpeakingPracticeContext = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetSpeakingPracticeContextData, ThrowOnError>,
): RequestResult<
  GetSpeakingPracticeContextResponses,
  GetSpeakingPracticeContextErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetSpeakingPracticeContextResponses,
    GetSpeakingPracticeContextErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/practice-context",
    ...options,
  });

/**
 * 驗證草稿，不保存或呼叫 AI
 */
export const validateSpeakingReview = <ThrowOnError extends boolean = false>(
  options: Options<ValidateSpeakingReviewData, ThrowOnError>,
): RequestResult<
  ValidateSpeakingReviewResponses,
  ValidateSpeakingReviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ValidateSpeakingReviewResponses,
    ValidateSpeakingReviewErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/reviews/validate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 保存確認過的文字與 Review，原子更新單字
 */
export const saveSpeakingReview = <ThrowOnError extends boolean = false>(
  options: Options<SaveSpeakingReviewData, ThrowOnError>,
): RequestResult<
  SaveSpeakingReviewResponses,
  SaveSpeakingReviewErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SaveSpeakingReviewResponses,
    SaveSpeakingReviewErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/reviews",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 搬移舊文字，不重新分析或計次
 */
export const migrateSpeakingHistory = <ThrowOnError extends boolean = false>(
  options: Options<MigrateSpeakingHistoryData, ThrowOnError>,
): RequestResult<
  MigrateSpeakingHistoryResponses,
  MigrateSpeakingHistoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    MigrateSpeakingHistoryResponses,
    MigrateSpeakingHistoryErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/history-migrations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 建立短期 CLI 登入授權
 */
export const createCliLoginAuthorization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCliLoginAuthorizationData, ThrowOnError>,
): RequestResult<
  CreateCliLoginAuthorizationResponses,
  CreateCliLoginAuthorizationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCliLoginAuthorizationResponses,
    CreateCliLoginAuthorizationErrors,
    ThrowOnError
  >({
    url: "/auth/cli/authorizations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 瀏覽器確認 CLI 帳號及配對碼
 */
export const approveCliLoginAuthorization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApproveCliLoginAuthorizationData, ThrowOnError>,
): RequestResult<
  ApproveCliLoginAuthorizationResponses,
  ApproveCliLoginAuthorizationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ApproveCliLoginAuthorizationResponses,
    ApproveCliLoginAuthorizationErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/auth/cli/authorizations/{id}/approve",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 由發起端單次兌換 session cookie
 */
export const exchangeCliLoginAuthorization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExchangeCliLoginAuthorizationData, ThrowOnError>,
): RequestResult<
  ExchangeCliLoginAuthorizationResponses,
  ExchangeCliLoginAuthorizationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ExchangeCliLoginAuthorizationResponses,
    ExchangeCliLoginAuthorizationErrors,
    ThrowOnError
  >({
    url: "/auth/cli/authorizations/{id}/exchange",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 註冊帳號
 *
 * 使用 Email 註冊新帳號，成功後設定 session cookie。
 */
export const register = <ThrowOnError extends boolean = false>(
  options: Options<RegisterData, ThrowOnError>,
): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> =>
  (options.client ?? client).post<
    RegisterResponses,
    RegisterErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 登入帳號
 *
 * 使用 Email + 密碼登入，成功後設定 session cookie。
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
): RequestResult<LoginResponses, LoginErrors, ThrowOnError> =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 登出帳號
 *
 * 撤銷目前 session 並清除 cookie。
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
    {
      security: [
        {
          in: "cookie",
          name: "session",
          type: "apiKey",
        },
      ],
      url: "/auth/logout",
      ...options,
    },
  );

/**
 * 發起 Google OAuth
 *
 * 重新導向至 Google 授權頁面。
 */
export const initiateGoogleOAuth = <ThrowOnError extends boolean = false>(
  options?: Options<InitiateGoogleOAuthData, ThrowOnError>,
): RequestResult<unknown, unknown, ThrowOnError> =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: "/auth/google",
    ...options,
  });

/**
 * Google OAuth Callback
 *
 * Google 授權完成後的回呼端點，驗證後設定 session cookie 並導向前端。
 */
export const handleGoogleOAuthCallback = <ThrowOnError extends boolean = false>(
  options: Options<HandleGoogleOAuthCallbackData, ThrowOnError>,
): RequestResult<unknown, HandleGoogleOAuthCallbackErrors, ThrowOnError> =>
  (options.client ?? client).get<
    unknown,
    HandleGoogleOAuthCallbackErrors,
    ThrowOnError
  >({ url: "/auth/google/callback", ...options });

/**
 * 取得目前使用者資訊
 *
 * 取得目前登入使用者的資訊。
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
): RequestResult<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetCurrentUserResponses,
    GetCurrentUserErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/auth/me",
    ...options,
  });

/**
 * 取得牌組列表
 *
 * 取得目前使用者的所有牌組列表，包含學習統計資訊。
 */
export const listDecks = <ThrowOnError extends boolean = false>(
  options?: Options<ListDecksData, ThrowOnError>,
): RequestResult<ListDecksResponses, ListDecksErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListDecksResponses,
    ListDecksErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks",
    ...options,
  });

/**
 * 建立新牌組
 *
 * 建立新牌組，成功後返回牌組資訊。
 */
export const createDeck = <ThrowOnError extends boolean = false>(
  options: Options<CreateDeckData, ThrowOnError>,
): RequestResult<CreateDeckResponses, CreateDeckErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateDeckResponses,
    CreateDeckErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 刪除牌組
 *
 * 刪除指定牌組及其所有卡片和學習紀錄。
 */
export const deleteDeck = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDeckData, ThrowOnError>,
): RequestResult<DeleteDeckResponses, DeleteDeckErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteDeckResponses,
    DeleteDeckErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{id}",
    ...options,
  });

/**
 * 取得牌組詳情
 *
 * 取得指定牌組的詳細資訊，包含學習統計。
 */
export const getDeck = <ThrowOnError extends boolean = false>(
  options: Options<GetDeckData, ThrowOnError>,
): RequestResult<GetDeckResponses, GetDeckErrors, ThrowOnError> =>
  (options.client ?? client).get<GetDeckResponses, GetDeckErrors, ThrowOnError>(
    {
      security: [
        {
          in: "cookie",
          name: "session",
          type: "apiKey",
        },
      ],
      url: "/decks/{id}",
      ...options,
    },
  );

/**
 * 更新牌組設定
 *
 * 更新指定牌組的設定。
 */
export const updateDeck = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDeckData, ThrowOnError>,
): RequestResult<UpdateDeckResponses, UpdateDeckErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateDeckResponses,
    UpdateDeckErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 匯出單一牌組
 *
 * 匯出指定牌組的持久設定與全部卡片內容，不包含學習紀錄與排程狀態。
 */
export const exportDeck = <ThrowOnError extends boolean = false>(
  options: Options<ExportDeckData, ThrowOnError>,
): RequestResult<ExportDeckResponses, ExportDeckErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ExportDeckResponses,
    ExportDeckErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{id}/export",
    ...options,
  });

/**
 * 匯入單一牌組
 *
 * 從 FlashMind 牌組 JSON 建立新牌組與卡片，不匯入學習紀錄或排程狀態。
 */
export const importDeck = <ThrowOnError extends boolean = false>(
  options: Options<ImportDeckData, ThrowOnError>,
): RequestResult<ImportDeckResponses, ImportDeckErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ImportDeckResponses,
    ImportDeckErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取得牌組內卡片列表
 *
 * 取得指定牌組內的所有卡片列表。
 */
export const listCards = <ThrowOnError extends boolean = false>(
  options: Options<ListCardsData, ThrowOnError>,
): RequestResult<ListCardsResponses, ListCardsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListCardsResponses,
    ListCardsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/cards",
    ...options,
  });

/**
 * 新增卡片
 *
 * 在指定牌組內新增卡片。
 */
export const createCard = <ThrowOnError extends boolean = false>(
  options: Options<CreateCardData, ThrowOnError>,
): RequestResult<CreateCardResponses, CreateCardErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateCardResponses,
    CreateCardErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/cards",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 刪除卡片
 *
 * 刪除指定卡片。
 */
export const deleteCard = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCardData, ThrowOnError>,
): RequestResult<DeleteCardResponses, DeleteCardErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteCardResponses,
    DeleteCardErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/cards/{cardId}",
    ...options,
  });

/**
 * 取得單張卡片
 *
 * 取得指定卡片的詳細資訊。
 */
export const getCard = <ThrowOnError extends boolean = false>(
  options: Options<GetCardData, ThrowOnError>,
): RequestResult<GetCardResponses, GetCardErrors, ThrowOnError> =>
  (options.client ?? client).get<GetCardResponses, GetCardErrors, ThrowOnError>(
    {
      security: [
        {
          in: "cookie",
          name: "session",
          type: "apiKey",
        },
      ],
      url: "/decks/{deckId}/cards/{cardId}",
      ...options,
    },
  );

/**
 * 更新卡片
 *
 * 更新指定卡片的內容。
 */
export const updateCard = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCardData, ThrowOnError>,
): RequestResult<UpdateCardResponses, UpdateCardErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateCardResponses,
    UpdateCardErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/cards/{cardId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 批次匯入卡片
 *
 * 透過 JSON 格式批次匯入卡片至指定牌組。支援部分成功模式，回傳每張卡片的匯入結果。
 */
export const importCards = <ThrowOnError extends boolean = false>(
  options: Options<ImportCardsData, ThrowOnError>,
): RequestResult<ImportCardsResponses, ImportCardsErrors, ThrowOnError> =>
  (options.client ?? client).post<
    ImportCardsResponses,
    ImportCardsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/cards/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取得目標單字
 *
 * 取得目前使用者的目標單字，支援狀態與關鍵字篩選。
 */
export const listTargetVocabulary = <ThrowOnError extends boolean = false>(
  options?: Options<ListTargetVocabularyData, ThrowOnError>,
): RequestResult<
  ListTargetVocabularyResponses,
  ListTargetVocabularyErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListTargetVocabularyResponses,
    ListTargetVocabularyErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/target-vocabulary",
    ...options,
  });

/**
 * 匯入目標單字
 *
 * 批次匯入目標單字，略過目標庫或使用者牌組中已存在的內容。
 */
export const importTargetVocabulary = <ThrowOnError extends boolean = false>(
  options: Options<ImportTargetVocabularyData, ThrowOnError>,
): RequestResult<
  ImportTargetVocabularyResponses,
  ImportTargetVocabularyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ImportTargetVocabularyResponses,
    ImportTargetVocabularyErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/target-vocabulary/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 將已使用的目標單字加入牌組
 *
 * 建立或連結使用者既有的同字卡，成功後將目標單字標記為已加入。
 */
export const addTargetVocabularyToDeck = <ThrowOnError extends boolean = false>(
  options: Options<AddTargetVocabularyToDeckData, ThrowOnError>,
): RequestResult<
  AddTargetVocabularyToDeckResponses,
  AddTargetVocabularyToDeckErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddTargetVocabularyToDeckResponses,
    AddTargetVocabularyToDeckErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/target-vocabulary/{id}/add-to-deck",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 撤銷目標單字的已使用判定
 *
 * 清除尚未加入牌組的使用記錄，並依推薦次數回到待練習或待接觸。
 */
export const rejectTargetVocabularyUse = <ThrowOnError extends boolean = false>(
  options: Options<RejectTargetVocabularyUseData, ThrowOnError>,
): RequestResult<
  RejectTargetVocabularyUseResponses,
  RejectTargetVocabularyUseErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RejectTargetVocabularyUseResponses,
    RejectTargetVocabularyUseErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/target-vocabulary/{id}/reject-use",
    ...options,
  });

/**
 * 取得收藏包項目
 *
 * 取得目前使用者的收藏包項目，支援分類、搜尋與 cursor-based 分頁。
 */
export const listCollectionItems = <ThrowOnError extends boolean = false>(
  options?: Options<ListCollectionItemsData, ThrowOnError>,
): RequestResult<
  ListCollectionItemsResponses,
  ListCollectionItemsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListCollectionItemsResponses,
    ListCollectionItemsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections",
    ...options,
  });

/**
 * 建立收藏包項目
 *
 * 使用者確認 AI 候選後，建立或更新收藏項目、關聯語塊與來源卡片連結。
 */
export const createCollectionItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateCollectionItemData, ThrowOnError>,
): RequestResult<
  CreateCollectionItemResponses,
  CreateCollectionItemErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCollectionItemResponses,
    CreateCollectionItemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 刪除收藏包項目
 *
 * 刪除目前使用者的指定收藏項目。
 */
export const deleteCollectionItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCollectionItemData, ThrowOnError>,
): RequestResult<
  DeleteCollectionItemResponses,
  DeleteCollectionItemErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCollectionItemResponses,
    DeleteCollectionItemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections/{id}",
    ...options,
  });

/**
 * 取得單筆收藏包項目
 */
export const getCollectionItem = <ThrowOnError extends boolean = false>(
  options: Options<GetCollectionItemData, ThrowOnError>,
): RequestResult<
  GetCollectionItemResponses,
  GetCollectionItemErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCollectionItemResponses,
    GetCollectionItemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections/{id}",
    ...options,
  });

/**
 * 更新收藏包句子
 */
export const updateCollectionItem = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCollectionItemData, ThrowOnError>,
): RequestResult<
  UpdateCollectionItemResponses,
  UpdateCollectionItemErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateCollectionItemResponses,
    UpdateCollectionItemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 建立收藏包聊天 session
 *
 * 建立新的收藏包 AI 聊天 session。
 */
export const createCollectionChatSession = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CreateCollectionChatSessionData, ThrowOnError>,
): RequestResult<
  CreateCollectionChatSessionResponses,
  CreateCollectionChatSessionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateCollectionChatSessionResponses,
    CreateCollectionChatSessionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections/chat-sessions",
    ...options,
  });

/**
 * 取得收藏包聊天訊息
 *
 * 取得收藏包聊天 session 內的歷史訊息與 assistant metadata。
 */
export const listCollectionChatMessages = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListCollectionChatMessagesData, ThrowOnError>,
): RequestResult<
  ListCollectionChatMessagesResponses,
  ListCollectionChatMessagesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListCollectionChatMessagesResponses,
    ListCollectionChatMessagesErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections/chat-sessions/{sessionId}/messages",
    ...options,
  });

/**
 * 送出收藏包聊天訊息
 *
 * 將使用者訊息送到收藏包 AI agent，回傳 AI 回覆與可收藏候選。
 */
export const createCollectionChatMessage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCollectionChatMessageData, ThrowOnError>,
): RequestResult<
  CreateCollectionChatMessageResponses,
  CreateCollectionChatMessageErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCollectionChatMessageResponses,
    CreateCollectionChatMessageErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/collections/chat-sessions/{sessionId}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取得主題對話歷史
 *
 * 依最近更新時間取得目前使用者的主題對話場次，支援 cursor-based 分頁。
 */
export const listTopicConversations = <ThrowOnError extends boolean = false>(
  options?: Options<ListTopicConversationsData, ThrowOnError>,
): RequestResult<
  ListTopicConversationsResponses,
  ListTopicConversationsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListTopicConversationsResponses,
    ListTopicConversationsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations",
    ...options,
  });

/**
 * 建立新的主題對話
 *
 * 使用先前產生的草稿建立場次並保存 AI 的英文開場訊息。只應在使用者送出第一則訊息時呼叫。
 */
export const createTopicConversation = <ThrowOnError extends boolean = false>(
  options: Options<CreateTopicConversationData, ThrowOnError>,
): RequestResult<
  CreateTopicConversationResponses,
  CreateTopicConversationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTopicConversationResponses,
    CreateTopicConversationErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 產生未持久化的主題草稿
 *
 * 產生盡量不與歷史重複的新主題與 AI 英文開場訊息，但不建立 Topic、Session 或 Message。
 */
export const createTopicConversationDraft = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CreateTopicConversationDraftData, ThrowOnError>,
): RequestResult<
  CreateTopicConversationDraftResponses,
  CreateTopicConversationDraftErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CreateTopicConversationDraftResponses,
    CreateTopicConversationDraftErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/draft",
    ...options,
  });

/**
 * 為未持久化的主題草稿產生提示
 */
export const createTopicConversationDraftHint = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTopicConversationDraftHintData, ThrowOnError>,
): RequestResult<
  CreateTopicConversationDraftHintResponses,
  CreateTopicConversationDraftHintErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTopicConversationDraftHintResponses,
    CreateTopicConversationDraftHintErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/draft/hint",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 刪除主題對話
 *
 * 刪除目前使用者指定的對話場次與其所有訊息。
 */
export const deleteTopicConversation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTopicConversationData, ThrowOnError>,
): RequestResult<
  DeleteTopicConversationResponses,
  DeleteTopicConversationErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTopicConversationResponses,
    DeleteTopicConversationErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/{id}",
    ...options,
  });

/**
 * 取得主題對話詳情
 *
 * 取得目前使用者指定場次的主題、完整訊息與文法修正，訊息依建立時間排序。
 */
export const getTopicConversation = <ThrowOnError extends boolean = false>(
  options: Options<GetTopicConversationData, ThrowOnError>,
): RequestResult<
  GetTopicConversationResponses,
  GetTopicConversationErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTopicConversationResponses,
    GetTopicConversationErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/{id}",
    ...options,
  });

/**
 * 送出主題對話訊息
 *
 * 保存使用者原始英文訊息，產生獨立的文法修正，並由 AI 以英文延續目前對話。
 */
export const createTopicConversationMessage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTopicConversationMessageData, ThrowOnError>,
): RequestResult<
  CreateTopicConversationMessageResponses,
  CreateTopicConversationMessageErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTopicConversationMessageResponses,
    CreateTopicConversationMessageErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/{id}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 串流送出主題對話訊息
 *
 * 立即保存使用者訊息，以 SSE 傳送 AI 回覆片段，完成後回傳正式訊息與文法修正結果。
 */
export const streamTopicConversationMessage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    StreamTopicConversationMessageData,
    ThrowOnError,
    StreamTopicConversationMessageResponse
  >,
): Promise<ServerSentEventsResult<StreamTopicConversationMessageResponses>> =>
  (options.client ?? client).sse.post<
    StreamTopicConversationMessageResponses,
    StreamTopicConversationMessageErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/{id}/messages/stream",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 產生主題對話提示
 *
 * 僅在使用者主動要求時，根據目前主題與對話歷史產生簡短回應建議，不會代替使用者送出訊息。
 */
export const createTopicConversationHint = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTopicConversationHintData, ThrowOnError>,
): RequestResult<
  CreateTopicConversationHintResponses,
  CreateTopicConversationHintErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTopicConversationHintResponses,
    CreateTopicConversationHintErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/{id}/hint",
    ...options,
  });

/**
 * 再練一次既有主題
 *
 * 沿用指定場次的主題建立新的練習場次與 AI 英文開場訊息，不修改原始場次。
 */
export const replayTopicConversation = <ThrowOnError extends boolean = false>(
  options: Options<ReplayTopicConversationData, ThrowOnError>,
): RequestResult<
  ReplayTopicConversationResponses,
  ReplayTopicConversationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ReplayTopicConversationResponses,
    ReplayTopicConversationErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/topic-conversations/{id}/replay",
    ...options,
  });

/**
 * AI 生成卡片內容
 *
 * 根據正面文字（單字/片語）使用 AI 生成詞義與例句。
 */
export const generateCardContent = <ThrowOnError extends boolean = false>(
  options: Options<GenerateCardContentData, ThrowOnError>,
): RequestResult<
  GenerateCardContentResponses,
  GenerateCardContentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    GenerateCardContentResponses,
    GenerateCardContentErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/ai/generate-card-content",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 取得今日學習卡片
 *
 * 取得指定牌組的今日學習卡片，包含待複習卡片和新卡片。待複習卡片優先，按 due 升序排列。
 */
export const getStudyCards = <ThrowOnError extends boolean = false>(
  options: Options<GetStudyCardsData, ThrowOnError>,
): RequestResult<GetStudyCardsResponses, GetStudyCardsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetStudyCardsResponses,
    GetStudyCardsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/study/cards",
    ...options,
  });

/**
 * 提交學習評分
 *
 * 對卡片提交學習評分，更新 FSRS 排程。
 */
export const submitReview = <ThrowOnError extends boolean = false>(
  options: Options<SubmitReviewData, ThrowOnError>,
): RequestResult<SubmitReviewResponses, SubmitReviewErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SubmitReviewResponses,
    SubmitReviewErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/study/review",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 產生關聯例句
 *
 * 使用使用者已熟練的字彙，為指定學習卡片產生新的例句預覽。此操作不會保存卡片。
 */
export const generateRelatedExample = <ThrowOnError extends boolean = false>(
  options: Options<GenerateRelatedExampleData, ThrowOnError>,
): RequestResult<
  GenerateRelatedExampleResponses,
  GenerateRelatedExampleErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    GenerateRelatedExampleResponses,
    GenerateRelatedExampleErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/study/cards/{cardId}/related-example",
    ...options,
  });

/**
 * 取得學習統計摘要
 *
 * 取得指定牌組的學習統計摘要。
 */
export const getStudySummary = <ThrowOnError extends boolean = false>(
  options: Options<GetStudySummaryData, ThrowOnError>,
): RequestResult<
  GetStudySummaryResponses,
  GetStudySummaryErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetStudySummaryResponses,
    GetStudySummaryErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/study/summary",
    ...options,
  });

/**
 * 設定今日學習上限覆寫
 *
 * 臨時提高指定牌組的今日新卡或複習上限。覆寫值必須大於或等於牌組預設值。隔天自動失效。
 */
export const setDailyOverride = <ThrowOnError extends boolean = false>(
  options: Options<SetDailyOverrideData, ThrowOnError>,
): RequestResult<
  SetDailyOverrideResponses,
  SetDailyOverrideErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    SetDailyOverrideResponses,
    SetDailyOverrideErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/decks/{deckId}/daily-override",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 文字轉語音
 *
 * 將英文文字轉換為語音，回傳 MP3 音訊。
 */
export const synthesizeSpeech = <ThrowOnError extends boolean = false>(
  options: Options<SynthesizeSpeechData, ThrowOnError>,
): RequestResult<
  SynthesizeSpeechResponses,
  SynthesizeSpeechErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SynthesizeSpeechResponses,
    SynthesizeSpeechErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/tts/synthesize",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 單字轉語音
 *
 * 將英文單字轉換為語音，使用 Google Translate TTS，回傳 MP3 音訊。
 */
export const synthesizeWord = <ThrowOnError extends boolean = false>(
  options: Options<SynthesizeWordData, ThrowOnError>,
): RequestResult<SynthesizeWordResponses, SynthesizeWordErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SynthesizeWordResponses,
    SynthesizeWordErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/tts/word",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 建立口說對話回覆
 *
 * 依使用者訊息與對話歷史生成口說練習回覆。
 */
export const createSpeakingReply = <ThrowOnError extends boolean = false>(
  options: Options<CreateSpeakingReplyData, ThrowOnError>,
): RequestResult<
  CreateSpeakingReplyResponses,
  CreateSpeakingReplyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSpeakingReplyResponses,
    CreateSpeakingReplyErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 建立語音口說對話回覆
 *
 * 上傳使用者錄音，回傳 AI 語音與逐字稿。
 */
export const createSpeakingAudioReply = <ThrowOnError extends boolean = false>(
  options: Options<CreateSpeakingAudioReplyData, ThrowOnError>,
): RequestResult<
  CreateSpeakingAudioReplyResponses,
  CreateSpeakingAudioReplyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSpeakingAudioReplyResponses,
    CreateSpeakingAudioReplyErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/chat/audio",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * 產生口說對話摘要
 *
 * 依據對話歷史生成摘要與標題。
 */
export const summarizeSpeakingConversation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SummarizeSpeakingConversationData, ThrowOnError>,
): RequestResult<
  SummarizeSpeakingConversationResponses,
  SummarizeSpeakingConversationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SummarizeSpeakingConversationResponses,
    SummarizeSpeakingConversationErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/summarize",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 翻譯口說回覆文字
 *
 * 將英語文字翻譯為繁體中文。
 */
export const translateSpeakingText = <ThrowOnError extends boolean = false>(
  options: Options<TranslateSpeakingTextData, ThrowOnError>,
): RequestResult<
  TranslateSpeakingTextResponses,
  TranslateSpeakingTextErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TranslateSpeakingTextResponses,
    TranslateSpeakingTextErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/translate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 口說 AI 助手對話
 *
 * 與口說練習內建 AI 助手對話。
 */
export const chatSpeakingAssistant = <ThrowOnError extends boolean = false>(
  options: Options<ChatSpeakingAssistantData, ThrowOnError>,
): RequestResult<
  ChatSpeakingAssistantResponses,
  ChatSpeakingAssistantErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ChatSpeakingAssistantResponses,
    ChatSpeakingAssistantErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/assistant/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 串流口說 AI 助手對話
 *
 * 以 Server-Sent Events 串流回傳文字與工具調用事件。
 */
export const streamSpeakingAssistant = <ThrowOnError extends boolean = false>(
  options: Options<
    StreamSpeakingAssistantData,
    ThrowOnError,
    StreamSpeakingAssistantResponse
  >,
): Promise<ServerSentEventsResult<StreamSpeakingAssistantResponses>> =>
  (options.client ?? client).sse.post<
    StreamSpeakingAssistantResponses,
    StreamSpeakingAssistantErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/assistant/chat/stream",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * 試聽口說語音
 *
 * 依指定 voice 產生試聽語音。
 */
export const previewSpeakingVoice = <ThrowOnError extends boolean = false>(
  options?: Options<PreviewSpeakingVoiceData, ThrowOnError>,
): RequestResult<
  PreviewSpeakingVoiceResponses,
  PreviewSpeakingVoiceErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PreviewSpeakingVoiceResponses,
    PreviewSpeakingVoiceErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "session",
        type: "apiKey",
      },
    ],
    url: "/speaking/voice-preview",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
