// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.flashmind.local" | (string & {});
};

/**
 * 錯誤回應（符合 ADR-016）
 */
export type ErrorResponse = {
  error: {
    /**
     * 機器可讀的錯誤碼（SCREAMING_SNAKE_CASE）
     */
    code: string;
    /**
     * 使用者可讀的錯誤訊息
     */
    message: string;
  };
};

/**
 * 分頁資訊（cursor-based）
 */
export type PaginationMeta = {
  /**
   * 下一頁的 cursor，若無更多資料則為 null
   */
  nextCursor?: string | null;
  /**
   * 是否還有更多資料
   */
  hasMore?: boolean;
};

/**
 * Email 註冊請求
 */
export type RegisterRequest = {
  email: string;
  /**
   * 密碼（至少 8 字元）
   */
  password: string;
};

/**
 * Email 登入請求
 */
export type LoginRequest = {
  email: string;
  password: string;
  /**
   * 記住我（延長 session 效期至 30 天）
   */
  rememberMe?: boolean;
};

/**
 * 使用者資料
 */
export type User = {
  /**
   * 使用者 ID（cuid）
   */
  id: string;
  email: string;
  /**
   * 主要登入方式
   */
  primaryProvider: "email" | "google";
  /**
   * 建立時間（ISO 8601 UTC）
   */
  createdAt: string;
  /**
   * 最後登入時間
   */
  lastLoginAt?: string | null;
};

/**
 * 使用者回應（符合 ADR-016 統一 Wrapper）
 */
export type UserResponse = {
  data: User;
};

/**
 * 牌組資料
 */
export type Deck = {
  /**
   * 牌組 ID（cuid）
   */
  id: string;
  /**
   * 牌組名稱
   */
  name: string;
  /**
   * 每日新卡數
   */
  dailyNewCards: number;
  /**
   * 每日複習數
   */
  dailyReviewCards: number;
  /**
   * 每日重置時間（0-23 時，預設 4 點）
   */
  dailyResetHour: number;
  /**
   * 學習步驟（逗號分隔，例如 "1m,10m"）
   */
  learningSteps?: string;
  /**
   * 重學步驟（逗號分隔，例如 "10m"）
   */
  relearningSteps?: string;
  /**
   * 目標保留率（0.70 ~ 0.97）
   */
  requestRetention?: number;
  /**
   * 最大複習間隔（天，30 ~ 36500）
   */
  maximumInterval?: number;
  /**
   * 是否啟用反向學習
   */
  enableReverse?: boolean;
  /**
   * 建立時間（ISO 8601 UTC）
   */
  createdAt: string;
  /**
   * 更新時間（ISO 8601 UTC）
   */
  updatedAt: string;
};

/**
 * 牌組列表項目（含學習統計）
 */
export type DeckListItem = {
  /**
   * 牌組 ID
   */
  id: string;
  /**
   * 牌組名稱
   */
  name: string;
  /**
   * 今日可學習新卡數
   */
  newCount: number;
  /**
   * 今日待複習數
   */
  reviewCount: number;
  /**
   * 總卡片數
   */
  totalCount: number;
  /**
   * 已完成學習的卡片數
   */
  completedCount: number;
  /**
   * 學習進度百分比（0-100）
   */
  progress: number;
  /**
   * 是否啟用反向學習
   */
  enableReverse?: boolean;
  /**
   * 每日新卡上限
   */
  dailyNewCards: number;
  /**
   * 每日複習上限
   */
  dailyReviewCards: number;
  /**
   * 今日已學新卡數
   */
  todayNewStudied: number;
  /**
   * 今日已複習數
   */
  todayReviewStudied: number;
};

/**
 * 牌組詳情（含學習統計）
 */
export type DeckDetail = {
  /**
   * 牌組 ID
   */
  id: string;
  /**
   * 牌組名稱
   */
  name: string;
  /**
   * 每日新卡數
   */
  dailyNewCards: number;
  /**
   * 每日複習數
   */
  dailyReviewCards: number;
  /**
   * 每日重置時間（0-23 時）
   */
  dailyResetHour: number;
  /**
   * 學習步驟（逗號分隔）
   */
  learningSteps?: string;
  /**
   * 重學步驟（逗號分隔）
   */
  relearningSteps?: string;
  /**
   * 目標保留率
   */
  requestRetention?: number;
  /**
   * 最大複習間隔（天）
   */
  maximumInterval?: number;
  /**
   * 是否啟用反向學習
   */
  enableReverse?: boolean;
  stats: DeckStats;
};

/**
 * 牌組學習統計
 */
export type DeckStats = {
  /**
   * 今日可學習新卡數
   */
  newCount: number;
  /**
   * 今日待複習數
   */
  reviewCount: number;
  /**
   * 總卡片數
   */
  totalCount: number;
  /**
   * 牌組建立時間
   */
  createdAt: string;
  /**
   * 上次學習時間
   */
  lastStudiedAt?: string | null;
};

/**
 * 建立牌組請求
 */
export type CreateDeckRequest = {
  /**
   * 牌組名稱（必填）
   */
  name: string;
  /**
   * 每日新卡數（預設 20）
   */
  dailyNewCards?: number;
  /**
   * 每日複習數（預設 100）
   */
  dailyReviewCards?: number;
  /**
   * 每日重置時間（0-23 時，預設 4 點）
   */
  dailyResetHour?: number;
  /**
   * 學習步驟（逗號分隔，預設 "1m,10m"）
   */
  learningSteps?: string;
  /**
   * 重學步驟（逗號分隔，預設 "10m"）
   */
  relearningSteps?: string;
  /**
   * 目標保留率（0.70 ~ 0.97，預設 0.9）
   */
  requestRetention?: number;
  /**
   * 最大複習間隔（天，30 ~ 36500，預設 36500）
   */
  maximumInterval?: number;
  /**
   * 是否啟用反向學習（預設 false）
   */
  enableReverse?: boolean;
};

/**
 * 更新牌組請求
 */
export type UpdateDeckRequest = {
  /**
   * 牌組名稱
   */
  name?: string;
  /**
   * 每日新卡數
   */
  dailyNewCards?: number;
  /**
   * 每日複習數
   */
  dailyReviewCards?: number;
  /**
   * 每日重置時間（0-23 時）
   */
  dailyResetHour?: number;
  /**
   * 學習步驟（逗號分隔）
   */
  learningSteps?: string;
  /**
   * 重學步驟（逗號分隔）
   */
  relearningSteps?: string;
  /**
   * 目標保留率（0.70 ~ 0.97）
   */
  requestRetention?: number;
  /**
   * 最大複習間隔（天，30 ~ 36500）
   */
  maximumInterval?: number;
  /**
   * 是否啟用反向學習
   */
  enableReverse?: boolean;
};

/**
 * 牌組回應（符合 ADR-016 統一 Wrapper）
 */
export type DeckResponse = {
  data: Deck;
};

/**
 * 牌組列表回應
 */
export type DeckListResponse = {
  data: Array<DeckListItem>;
};

/**
 * 牌組詳情回應
 */
export type DeckDetailResponse = {
  data: DeckDetail;
};

export type DeckExportMeaning = {
  /**
   * 中文詞義
   */
  zhMeaning: string;
  /**
   * 英文例句
   */
  enExample: string | null;
  /**
   * 中文例句
   */
  zhExample: string | null;
  /**
   * 詞義顯示順序
   */
  sortOrder: number;
};

export type DeckExportCard = {
  /**
   * 卡片正面內容
   */
  front: string;
  /**
   * 卡片備註；舊版匯入資料可省略
   */
  note?: string | null;
  meanings: Array<DeckExportMeaning>;
};

export type DeckExport = {
  /**
   * 匯出格式版本
   */
  version: 1;
  name: string;
  dailyNewCards: number;
  dailyReviewCards: number;
  dailyResetHour: number;
  learningSteps: string;
  relearningSteps: string;
  requestRetention: number;
  maximumInterval: number;
  enableReverse: boolean;
  cards: Array<DeckExportCard>;
};

export type DeckExportResponse = {
  data: DeckExport;
};

export type DeckImportResponse = {
  data: {
    id: string;
    name: string;
  };
};

/**
 * 卡片詞義
 */
export type CardMeaning = {
  /**
   * 詞義 ID
   */
  id: string;
  /**
   * 中文解釋（必填）
   */
  zhMeaning: string;
  /**
   * 英文例句
   */
  enExample?: string | null;
  /**
   * 中文例句翻譯
   */
  zhExample?: string | null;
};

/**
 * 卡片資料
 */
export type Card = {
  /**
   * 卡片 ID（cuid）
   */
  id: string;
  /**
   * 正面內容（單字/片語/問題）
   */
  front: string;
  /**
   * 使用者的卡片純文字備註
   */
  note: string | null;
  /**
   * 詞義列表
   */
  meanings: Array<CardMeaning>;
  /**
   * 建立時間（ISO 8601 UTC）
   */
  createdAt: string;
  /**
   * 更新時間（ISO 8601 UTC）
   */
  updatedAt: string;
};

/**
 * 卡片列表項目
 */
export type CardListItem = {
  /**
   * 列表項目 ID
   */
  id: string;
  /**
   * 底層卡片 ID
   */
  cardId: string;
  /**
   * 列表項目的學習方向
   */
  direction: "FORWARD" | "REVERSE";
  /**
   * 正面內容
   */
  front: string;
  /**
   * 摘要（第一筆詞義的中文解釋）
   */
  summary: string;
  /**
   * 該方向的卡片學習狀態
   */
  state: "NEW" | "LEARNING" | "REVIEW" | "RELEARNING";
  /**
   * 該方向的下次複習時間（ISO 8601 UTC），新卡片為 null
   */
  due?: string | null;
  /**
   * 該方向目前的熟練度；新卡片或排程資料不足時為 null
   */
  proficiency: "PROFICIENT" | "FAIR" | "UNSTABLE" | "NEEDS_WORK";
};

/**
 * 建立詞義請求
 */
export type CreateCardMeaningRequest = {
  /**
   * 中文解釋（必填）
   */
  zhMeaning: string;
  /**
   * 英文例句
   */
  enExample?: string;
  /**
   * 中文例句翻譯
   */
  zhExample?: string;
};

/**
 * 建立卡片請求
 */
export type CreateCardRequest = {
  /**
   * 正面內容（必填）
   */
  front: string;
  /**
   * 卡片純文字備註
   */
  note?: string | null;
  /**
   * 詞義列表（至少一筆）
   */
  meanings: Array<CreateCardMeaningRequest>;
};

/**
 * 更新詞義請求
 */
export type UpdateCardMeaningRequest = {
  /**
   * 詞義 ID（若有則更新，若無則新增）
   */
  id?: string;
  /**
   * 中文解釋
   */
  zhMeaning?: string;
  /**
   * 英文例句
   */
  enExample?: string | null;
  /**
   * 中文例句翻譯
   */
  zhExample?: string | null;
};

/**
 * 更新卡片請求
 */
export type UpdateCardRequest = {
  /**
   * 正面內容
   */
  front?: string;
  /**
   * 卡片純文字備註；空字串或 null 代表清除
   */
  note?: string | null;
  /**
   * 詞義列表（整包替換）
   */
  meanings?: Array<UpdateCardMeaningRequest>;
};

/**
 * 卡片回應（符合 ADR-016 統一 Wrapper）
 */
export type CardResponse = {
  data: Card;
};

/**
 * 卡片列表回應
 */
export type CardListResponse = {
  data: Array<CardListItem>;
};

/**
 * 批次匯入卡片請求
 */
export type ImportCardsRequest = {
  /**
   * 要匯入的卡片列表
   */
  cards: Array<CreateCardRequest>;
};

/**
 * 單張卡片匯入錯誤
 */
export type ImportCardError = {
  /**
   * 錯誤卡片在陣列中的索引（從 0 開始）
   */
  index: number;
  /**
   * 錯誤訊息
   */
  message: string;
};

/**
 * 批次匯入結果
 */
export type ImportCardsResult = {
  /**
   * 匯入卡片總數
   */
  total: number;
  /**
   * 成功匯入數量
   */
  success: number;
  /**
   * 失敗數量
   */
  failed: number;
  /**
   * 錯誤詳情列表
   */
  errors: Array<ImportCardError>;
};

/**
 * 批次匯入卡片回應（符合 ADR-016 統一 Wrapper）
 */
export type ImportCardsResponse = {
  data: ImportCardsResult;
};

export type TargetVocabularyStatus = "UNSEEN" | "PRACTICING" | "USED" | "ADDED";

export type TargetVocabularyItem = {
  id: string;
  term: string;
  normalizedTerm: string;
  zhMeaning: string;
  status: TargetVocabularyStatus;
  recommendationCount: number;
  useCount: number;
  expressionContext?: string | null;
  naturalSentence?: string | null;
  recommendationReason?: string | null;
  addedCardId?: string | null;
  addedAt?: string | null;
  createdAt: string;
  updatedAt: string;
};

export type TargetVocabularyListResponse = {
  data: Array<TargetVocabularyItem>;
};

export type ImportTargetVocabularyWord = {
  term: string;
  zhMeaning: string;
};

export type ImportTargetVocabularyRequest = {
  words: Array<ImportTargetVocabularyWord>;
};

export type ImportTargetVocabularyResult = {
  total: number;
  added: number;
  alreadyInTargets: number;
  alreadyInCards: number;
};

export type ImportTargetVocabularyResponse = {
  data: ImportTargetVocabularyResult;
};

export type AddTargetVocabularyToDeckRequest = {
  deckId: string;
  term: string;
  zhMeaning: string;
  naturalSentence?: string;
  /**
   * 自然句子的繁體中文翻譯
   */
  zhExample?: string;
};

export type AddTargetVocabularyToDeckResponse = {
  data: TargetVocabularyItem;
};

export type RejectTargetVocabularyUseResponse = {
  data: TargetVocabularyItem;
};

/**
 * 收藏項目類型
 */
export type CollectionItemKind =
  | "sentence"
  | "collocation"
  | "phrase"
  | "clause";

/**
 * 收藏項目語意關聯類型
 */
export type CollectionRelationType =
  | "sentence_has_collocation"
  | "sentence_has_phrase"
  | "sentence_has_clause"
  | "phrase_has_collocation"
  | "clause_has_collocation";

/**
 * 收藏包聊天 AI 判斷的使用者意圖
 */
export type CollectionChatIntent =
  | "translate_only"
  | "analyze_sentence"
  | "find_existing"
  | "suggest_candidates"
  | "correct_sentence"
  | "explain_usage";

/**
 * 收藏包聊天訊息角色
 */
export type CollectionChatRole = "user" | "assistant";

export type CollectionSourceCard = {
  /**
   * 卡片 ID
   */
  id: string;
  /**
   * 卡片正面文字
   */
  text: string;
  /**
   * 第一筆中文詞義
   */
  meaning?: string | null;
};

export type CollectionBreakdownItem = {
  /**
   * 收藏項目或候選項目 ID
   */
  id: string;
  kind: CollectionItemKind;
  text: string;
  meaning: string;
  sourceWord?: string | null;
  /**
   * 若已收藏，對應的收藏項目 ID
   */
  collectionItemId?: string | null;
};

export type CollectionRelatedSentence = {
  id: string;
  text: string;
  meaning: string;
};

export type CollectionItem = {
  id: string;
  kind: CollectionItemKind;
  text: string;
  meaning: string;
  sourceWords: Array<string>;
  sourceCards?: Array<CollectionSourceCard>;
  breakdownItems: Array<CollectionBreakdownItem>;
  relatedChunks: Array<CollectionBreakdownItem>;
  relatedSentences: Array<CollectionRelatedSentence>;
  createdAt: string;
  updatedAt: string;
};

export type CollectionItemListResponse = {
  data: Array<CollectionItem>;
  meta: PaginationMeta;
};

export type CollectionItemResponse = {
  data: CollectionItem;
};

export type CollectionSaveRelatedCandidate = {
  type: CollectionRelationType;
  kind: CollectionItemKind;
  text: string;
  meaning?: string | null;
  sourceCardIds?: Array<string>;
  sortOrder?: number;
};

export type CreateCollectionItemRequest = {
  kind: CollectionItemKind;
  text: string;
  meaning?: string | null;
  /**
   * 使用者既有卡片 ID
   */
  sourceCardIds?: Array<string>;
  /**
   * 使用者確認此候選時要一併保存的關聯語塊
   */
  relatedCandidates?: Array<CollectionSaveRelatedCandidate>;
};

export type UpdateCollectionItemRequest = {
  text: string;
  meaning?: string | null;
};

export type CollectionSuggestion = {
  /**
   * 候選 ID，可由 AI 或後端產生
   */
  id: string;
  kind: CollectionItemKind;
  text: string;
  meaning: string;
  sourceWord?: string | null;
  sourceCards?: Array<CollectionSourceCard>;
  /**
   * 是否已存在於收藏包
   */
  existing: boolean;
  /**
   * 前端是否已在本次互動加入
   */
  added: boolean;
  /**
   * 已存在或已加入時的收藏項目 ID
   */
  collectionItemId?: string | null;
  relatedCandidates?: Array<CollectionSaveRelatedCandidate>;
};

export type CollectionSuggestedCard = {
  /**
   * 候選 ID，可由 AI 或後端產生
   */
  id: string;
  front: string;
  meanings: Array<CreateCardMeaningRequest>;
  reason: string;
  /**
   * 若已存在於使用者卡片中，對應的卡片 ID
   */
  existingCardId?: string | null;
  /**
   * 前端是否已在本次互動建立卡片
   */
  added?: boolean;
};

export type CollectionChatSession = {
  id: string;
  title?: string | null;
  createdAt: string;
  updatedAt: string;
};

export type CollectionChatSessionResponse = {
  data: CollectionChatSession;
};

export type CreateCollectionChatMessageRequest = {
  message: string;
};

export type CollectionChatMessageResult = {
  sessionId: string;
  userMessage: string;
  assistantMessage: string;
  intent: CollectionChatIntent;
  candidates: Array<CollectionSuggestion>;
  suggestedCards: Array<CollectionSuggestedCard>;
};

export type CollectionChatMessageResponse = {
  data: CollectionChatMessageResult;
};

export type CollectionChatMessageItem = {
  id: string;
  role: CollectionChatRole;
  content: string;
  intent?: CollectionChatIntent | null;
  candidates: Array<CollectionSuggestion>;
  suggestedCards: Array<CollectionSuggestedCard>;
  createdAt: string;
};

export type CollectionChatMessageListResponse = {
  data: Array<CollectionChatMessageItem>;
};

/**
 * 主題對話訊息角色
 */
export type TopicConversationRole = "user" | "assistant";

/**
 * 使用者訊息的文法與自然度檢查結果：
 * - correct：句子自然正確，不需改寫
 * - improved：句子可理解且文法正確，但有更自然的說法
 * - corrected：句子有文法或明顯用字問題
 *
 */
export type TopicConversationCorrectionStatus =
  | "correct"
  | "improved"
  | "corrected";

/**
 * 使用者擁有的主題對話題目
 */
export type TopicConversationTopic = {
  /**
   * 主題 ID
   */
  id: string;
  /**
   * 主題標題
   */
  title: string;
  /**
   * 對話情境說明
   */
  scenario: string;
  /**
   * 主題建立時間
   */
  createdAt: string;
  updatedAt: string;
};

/**
 * 尚未寫入資料庫的主題對話草稿
 */
export type TopicConversationDraft = {
  title: string;
  scenario: string;
  /**
   * 主題更新時間
   */
  openingMessage: string;
};

/**
 * 與正常聊天回覆分開呈現的使用者訊息修正
 */
export type TopicConversationCorrection = {
  status: TopicConversationCorrectionStatus;
  /**
   * 建議句；status 為 correct 時為 null
   */
  suggestedText: string | null;
  /**
   * 繁體中文的簡短修正說明；不需修正時為 null
   */
  explanation: string | null;
};

/**
 * 主題對話中的單則訊息
 */
export type TopicConversationMessage = {
  /**
   * 訊息 ID
   */
  id: string;
  role: TopicConversationRole;
  /**
   * 使用者原始訊息或 AI 的英文對話內容
   */
  content: string;
  /**
   * 使用者訊息的修正；AI 訊息與尚未完成修正的訊息為 null
   */
  correction: TopicConversationCorrection | null;
  /**
   * 訊息建立時間
   */
  createdAt: string;
};

/**
 * 主題對話歷史列表中的場次摘要
 */
export type TopicConversationSessionSummary = {
  /**
   * 對話場次 ID
   */
  id: string;
  topic: TopicConversationTopic;
  /**
   * 場次內的訊息總數
   */
  messageCount: number;
  /**
   * 最近一則訊息摘要
   */
  lastMessagePreview: string;
  /**
   * 場次建立時間
   */
  createdAt: string;
  /**
   * 場次最近更新時間
   */
  updatedAt: string;
};

/**
 * 含完整訊息與修正的主題對話場次
 */
export type TopicConversationSessionDetail = {
  /**
   * 對話場次 ID
   */
  id: string;
  topic: TopicConversationTopic;
  /**
   * 依建立時間排序的完整訊息
   */
  messages: Array<TopicConversationMessage>;
  /**
   * 場次建立時間
   */
  createdAt: string;
  /**
   * 場次最近更新時間
   */
  updatedAt: string;
};

/**
 * 送出主題對話訊息的請求
 */
export type CreateTopicConversationMessageRequest = {
  /**
   * 使用者自由輸入的完整英文訊息
   */
  message: string;
};

/**
 * 一輪主題對話產生的使用者訊息、修正與 AI 回覆
 */
export type TopicConversationMessageExchange = {
  userMessage: TopicConversationMessage;
  assistantMessage: TopicConversationMessage;
};

/**
 * 使用者主動要求的回應提示
 */
export type TopicConversationHint = {
  /**
   * 根據目前上下文產生的簡短英文回應建議
   */
  suggestions: Array<string>;
};

/**
 * 主題對話歷史列表回應（符合 ADR-016 統一 Wrapper）
 */
export type TopicConversationSessionListResponse = {
  data: Array<TopicConversationSessionSummary>;
  meta: PaginationMeta;
};

/**
 * 主題對話場次詳情回應（符合 ADR-016 統一 Wrapper）
 */
export type TopicConversationSessionDetailResponse = {
  data: TopicConversationSessionDetail;
};

/**
 * 主題對話訊息回應（符合 ADR-016 統一 Wrapper）
 */
export type TopicConversationMessageResponse = {
  data: TopicConversationMessageExchange;
};

/**
 * 主題對話提示回應（符合 ADR-016 統一 Wrapper）
 */
export type TopicConversationHintResponse = {
  data: TopicConversationHint;
};

/**
 * AI 生成卡片內容請求
 */
export type GenerateCardContentRequest = {
  /**
   * 正面文字（單字/片語）
   */
  text: string;
};

/**
 * AI 生成的詞義
 */
export type GeneratedMeaning = {
  /**
   * 中文解釋
   */
  zhMeaning: string;
  /**
   * 英文例句
   */
  enExample?: string | null;
  /**
   * 中文例句翻譯
   */
  zhExample?: string | null;
};

/**
 * AI 生成卡片內容回應（符合 ADR-016 統一 Wrapper）
 */
export type GenerateCardContentResponse = {
  data: {
    /**
     * 生成的詞義列表
     */
    meanings: Array<GeneratedMeaning>;
  };
};

/**
 * OpenAI 語音角色
 */
export type SpeakingVoice =
  | "alloy"
  | "ash"
  | "ballad"
  | "coral"
  | "cedar"
  | "echo"
  | "marin"
  | "sage"
  | "shimmer"
  | "verse";

/**
 * 口說聊天歷史訊息
 */
export type SpeakingChatMessage = {
  /**
   * 訊息角色
   */
  role: "user" | "assistant";
  /**
   * 訊息內容
   */
  content: string;
};

/**
 * 口說聊天請求
 */
export type SpeakingChatRequest = {
  /**
   * 使用者本回合訊息
   */
  message: string;
  /**
   * 對話歷史（純文字）
   */
  history?: Array<SpeakingChatMessage>;
  /**
   * 可覆蓋預設提示詞
   */
  systemPrompt?: string;
};

/**
 * 口說語音端點歷史訊息
 */
export type SpeakingChatHistoryItem = {
  /**
   * 穩定訊息識別，供 Summary 原文證據引用
   */
  id?: string;
  /**
   * 訊息角色
   */
  role: "user" | "assistant";
  /**
   * 訊息文字內容（assistant 必填）
   */
  text?: string | null;
  /**
   * 使用者語音 base64（user 可用）
   */
  audioBase64?: string | null;
};

/**
 * 語音口說對話請求（multipart/form-data）
 */
export type SpeakingAudioChatMultipartRequest = {
  /**
   * 使用者錄音檔（建議 WAV 16k）
   */
  audioFile: Blob | File;
  /**
   * JSON 字串格式的歷史訊息陣列（SpeakingChatHistoryItem[]）
   */
  history?: string;
  voice?: SpeakingVoice;
  /**
   * 可覆蓋預設提示詞
   */
  systemPrompt?: string;
  /**
   * 長期記憶內容（選填）
   */
  memory?: string;
  /**
   * 是否啟用自動記憶更新（true/false）
   */
  autoMemoryEnabled?: string;
};

/**
 * token 使用量
 */
export type SpeakingTokenUsage = {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  promptTextTokens: number;
  promptAudioTokens: number;
  completionTextTokens: number;
  completionAudioTokens: number;
};

/**
 * 口說聊天結果
 */
export type SpeakingChatResult = {
  /**
   * AI 助教回覆
   */
  reply: string;
  /**
   * 實際使用的模型名稱
   */
  model: string;
  usage: SpeakingTokenUsage;
};

/**
 * 口說聊天回應（符合 ADR-016 統一 Wrapper）
 */
export type SpeakingChatResponse = {
  data: SpeakingChatResult;
};

/**
 * 自動記憶更新結果
 */
export type SpeakingMemoryUpdate = {
  /**
   * 更新後的完整記憶內容
   */
  memory: string;
  /**
   * 更新原因
   */
  reason?: string | null;
};

/**
 * 語音口說對話結果
 */
export type SpeakingAudioChatResult = {
  /**
   * AI 回覆逐字稿
   */
  transcript: string;
  /**
   * AI 回覆語音（base64）
   */
  audioBase64: string;
  /**
   * 實際使用的模型名稱
   */
  model: string;
  usage: SpeakingTokenUsage;
  memoryUpdate?: SpeakingMemoryUpdate | null;
};

/**
 * 語音口說對話回應（符合 ADR-016 統一 Wrapper）
 */
export type SpeakingAudioChatResponse = {
  data: SpeakingAudioChatResult;
};

/**
 * 口說摘要請求
 */
export type SpeakingSummarizeRequest = {
  history: Array<SpeakingChatHistoryItem>;
};

/**
 * 口說摘要分析結果；此請求不更新單字、不保存 Review，須另行呼叫 saveSpeakingReview
 */
export type SpeakingSummaryResult = {
  /**
   * 摘要標題（繁中）
   */
  title: string;
  /**
   * 對話摘要（英文第一人稱）
   */
  summary: string;
  /**
   * 本次口說練習回顧（繁中）
   */
  review: string;
  /**
   * 使用者在本次對話中實際使用的目標單字
   */
  actualUses: Array<SpeakingReviewUse>;
  /**
   * 依本次對話推薦下次可嘗試使用的目標單字
   */
  recommendations: Array<SpeakingReviewRecommendation>;
  nextPractice: SpeakingNextPractice;
  usage: SpeakingTokenUsage;
};

export type SpeakingReviewUse = {
  /**
   * 此帳號的目標單字識別
   */
  targetVocabularyId?: string;
  /**
   * 實際使用的原文證據，推薦項目不需要
   */
  evidence?: Array<SpeakingReviewEvidence>;
  term: string;
  zhMeaning: string;
  expressionContext: string;
  naturalSentence: string;
};

export type SpeakingReviewRecommendation = SpeakingReviewUse & {
  recommendationReason: string;
};

export type SpeakingNextPractice = {
  topic: string;
  speakingGoal: string;
  guidingQuestions: Array<string>;
  recallTargets: Array<string>;
};

/**
 * 口說摘要回應（符合 ADR-016 統一 Wrapper）
 */
export type SpeakingSummarizeResponse = {
  data: SpeakingSummaryResult;
};

/**
 * 口說翻譯請求
 */
export type SpeakingTranslateRequest = {
  text: string;
};

/**
 * 口說翻譯回應（符合 ADR-016 統一 Wrapper）
 */
export type SpeakingTranslateResponse = {
  data: {
    translatedText: string;
  };
};

/**
 * AI 助手歷史訊息
 */
export type SpeakingAssistantMessage = {
  role: "user" | "assistant";
  content: string;
};

/**
 * AI 助手對話請求
 */
export type SpeakingAssistantChatRequest = {
  message: string;
  history?: Array<SpeakingAssistantMessage>;
  /**
   * 推理努力程度；none 不額外啟用推理，max 對應模型可用的最高程度。
   */
  effort?: "none" | "low" | "medium" | "high" | "xhigh" | "max";
};

/**
 * AI 助手對話結果
 */
export type SpeakingAssistantChatResult = {
  reply: string;
  model: string;
  usage: SpeakingTokenUsage;
  /**
   * 本回合實際調用的工具
   */
  toolCalls: Array<{
    /**
     * 工具名稱
     */
    name: string;
    /**
     * OpenAI 工具調用識別碼
     */
    callId?: string;
    /**
     * 工具調用參數 JSON
     */
    arguments?: string;
    /**
     * 工具執行結果
     */
    result?: unknown;
  }>;
};

/**
 * AI 助手對話回應（符合 ADR-016 統一 Wrapper）
 */
export type SpeakingAssistantChatResponse = {
  data: SpeakingAssistantChatResult;
};

/**
 * 語音試聽請求
 */
export type SpeakingVoicePreviewRequest = {
  voice?: SpeakingVoice;
};

/**
 * 語音試聽回應（符合 ADR-016 統一 Wrapper）
 */
export type SpeakingVoicePreviewResponse = {
  data: {
    /**
     * MP3 試聽音訊（base64）
     */
    audioBase64: string;
  };
};

/**
 * 學習用卡片資料
 */
export type StudyCard = {
  /**
   * 卡片 ID
   */
  id: string;
  /**
   * 正面內容（單字/片語）
   */
  front: string;
  /**
   * 使用者的卡片純文字備註
   */
  note: string | null;
  /**
   * 詞義列表
   */
  meanings: Array<CardMeaning>;
  /**
   * 卡片狀態
   */
  state: "NEW" | "LEARNING" | "REVIEW" | "RELEARNING";
  /**
   * 是否為新卡
   */
  isNew: boolean;
  /**
   * 學習方向（FORWARD 正向、REVERSE 反向）
   */
  direction: "FORWARD" | "REVERSE";
};

/**
 * 學習卡片列表回應
 */
export type StudyCardsResponse = {
  data: Array<StudyCard>;
};

export type RelatedExample = {
  /**
   * 目標單字在例句中的中文解釋
   */
  zhMeaning: string;
  /**
   * 新的英文例句
   */
  enExample: string;
  /**
   * 新例句的中文翻譯
   */
  zhExample: string;
  /**
   * 例句中可能尚未學過、前端需要標亮的英文內容單字
   */
  unfamiliarWords?: Array<string>;
  /**
   * 例句中目前正在學習、前端需要以另一種顏色標亮的英文單字
   */
  learningWords?: Array<string>;
};

export type RelatedExampleResponse = {
  data: RelatedExample;
};

/**
 * 提交學習評分請求
 */
export type SubmitReviewRequest = {
  /**
   * 卡片 ID
   */
  cardId: string;
  /**
   * 評分
   * - known: 知道（右滑）
   * - unfamiliar: 不熟（上滑）
   * - unknown: 不知道（左滑）
   *
   */
  rating: "known" | "unfamiliar" | "unknown";
  /**
   * 學習方向（FORWARD 正向、REVERSE 反向）
   */
  direction?: "FORWARD" | "REVERSE";
};

/**
 * 評分結果
 */
export type ReviewResult = {
  /**
   * 卡片 ID
   */
  cardId: string;
  /**
   * 使用者評分
   */
  rating: "known" | "unfamiliar" | "unknown";
  /**
   * 下次複習時間
   */
  nextDue: string;
  /**
   * 評分後的卡片狀態
   */
  newState: "NEW" | "LEARNING" | "REVIEW" | "RELEARNING";
};

/**
 * 評分結果回應
 */
export type ReviewResultResponse = {
  data: ReviewResult;
};

/**
 * 學習統計摘要
 */
export type StudySummary = {
  /**
   * 總卡片數
   */
  totalCards: number;
  /**
   * 新卡數
   */
  newCount: number;
  /**
   * 待複習數
   */
  reviewCount: number;
  /**
   * 今日已學習數
   */
  todayStudied: number;
  /**
   * 牌組每日新卡上限
   */
  dailyNewCards: number;
  /**
   * 牌組每日複習上限
   */
  dailyReviewCards: number;
  /**
   * 今日已學新卡數
   */
  todayNewStudied: number;
  /**
   * 今日已複習數
   */
  todayReviewStudied: number;
};

/**
 * 學習統計摘要回應
 */
export type StudySummaryResponse = {
  data: StudySummary;
};

/**
 * 設定今日學習上限覆寫
 */
export type SetDailyOverrideRequest = {
  /**
   * 今日新卡上限覆寫（必須 >= 牌組預設值）
   */
  newCards?: number;
  /**
   * 今日複習上限覆寫（必須 >= 牌組預設值）
   */
  reviewCards?: number;
};

/**
 * 覆寫設定成功回應
 */
export type SetDailyOverrideResponse = {
  data: {
    /**
     * 設定後的有效新卡上限
     */
    effectiveNewCards: number;
    /**
     * 設定後的有效複習上限
     */
    effectiveReviewCards: number;
  };
};

/**
 * TTS 語音合成請求（句子用，使用 Azure TTS）
 */
export type SynthesizeSpeechRequest = {
  /**
   * 要合成的英文句子
   */
  text: string;
};

/**
 * TTS 單字合成請求（單字用，使用 Google Translate TTS）
 */
export type SynthesizeWordRequest = {
  /**
   * 要合成的英文單字
   */
  text: string;
};

export type CliAuthorizationApprove = {
  pairingCode: string;
  decision: "approve" | "deny";
  /**
   * 頁面確認的帳號；須與當前 session 相同，避免另一分頁切換帳號後誤寫
   */
  expectedUserId: string;
};

export type CliAuthorizationCreate = {
  verifierHash: string;
};

export type CliAuthorizationExchange = {
  verifier: string;
};

export type CliAuthorizationStarted = {
  authorizationId: string;
  verificationUrl: string;
  pairingCode: string;
  expiresAt: string;
  pollIntervalMs: number;
};

export type CliAuthorizationStatus = {
  status: "pending" | "approved" | "denied";
  expiresAt: string;
  userId: string | null;
  email: string | null;
};

export type SpeakingContextWord = {
  id: string;
  term: string;
  zhMeaning: string;
  status: "UNSEEN" | "PRACTICING" | "USED" | "ADDED";
  useCount: number;
  recommendationCount: number;
  expressionContext: string | null;
  naturalSentence: string | null;
  recommendationReason: string | null;
  addedCardId: string | null;
};

export type SpeakingHistoryError = {
  error: {
    code: string;
    message: string;
    details?: Array<SpeakingValidationIssue>;
  };
};

export type SpeakingHistoryMessage = {
  id: string;
  role: "user" | "assistant";
  text: string;
  createdAt: string;
  translatedText?: string;
  hasOriginalAudio?: boolean;
  transcriptStatus?: "available" | "unavailable";
};

export type SpeakingHistoryMigration = {
  sessions: Array<SpeakingLegacySession>;
  /**
   * 頁面確認的帳號；須與當前 session 相同，避免另一分頁切換帳號後誤寫
   */
  expectedUserId: string;
};

export type SpeakingHistoryPageMeta = {
  nextCursor: string | null;
  hasMore: boolean;
};

export type SpeakingHistorySource = "APP" | "LOCAL";

export type SpeakingLegacySession = {
  clientSessionId: string;
  title: string;
  startedAt: string;
  endedAt: string;
  messages: Array<SpeakingHistoryMessage>;
  summaries: Array<SpeakingLegacySummaryInput>;
  legacyPracticeContext?: {
    summaryId: string;
    plan: SpeakingPracticePlan;
  };
};

export type SpeakingLegacySummaryInput = {
  id: string;
  text: string;
  createdAt: string;
  ordinal: number;
};

export type SpeakingMessagesAppend = {
  revision: number;
  messages: Array<SpeakingHistoryMessage>;
  endedAt?: string;
  /**
   * 頁面確認的帳號；須與當前 session 相同，避免另一分頁切換帳號後誤寫
   */
  expectedUserId: string;
};

export type SpeakingMigrationResult = {
  clientSessionId: string;
  sessionId: string | null;
  status: "imported" | "alreadyImported" | "conflict" | "failed";
  message: string | null;
};

export type SpeakingPracticeContext = {
  schemaVersion: 1;
  userId: string;
  generatedAt: string;
  vocabularyVersion: string;
  vocabularyCount: number;
  targetVocabulary: Array<SpeakingContextWord>;
  lastPractice: {
    sessionId: string;
    source: SpeakingHistorySource;
    title: string;
    summary: string;
    startedAt: string;
    endedAt: string;
  } | null;
  nextPractice: SpeakingPracticePlan;
};

export type SpeakingPracticePlan = {
  topic: string;
  speakingGoal: string;
  guidingQuestions: Array<string>;
  recallTargets: Array<string>;
};

export type SpeakingRecordedRecommendation = {
  targetVocabularyId: string;
  term: string;
  expressionContext: string;
  naturalSentence: string;
  recommendationReason: string;
};

export type SpeakingRecordedResult = {
  summary: string;
  review: string;
  actualUses: Array<SpeakingRecordedUse>;
  recommendations: Array<SpeakingRecordedRecommendation>;
  nextPractice: SpeakingPracticePlan;
  deckCandidates: Array<string>;
};

export type SpeakingRecordedUse = {
  targetVocabularyId: string;
  term: string;
  expressionContext: string;
  naturalSentence: string;
  evidence: Array<SpeakingReviewEvidence>;
};

export type SpeakingReviewDraft = {
  schemaVersion: 1;
  target: {
    apiOrigin: string;
    userId: string;
  };
  contextVersion: string;
  practice: {
    source: SpeakingHistorySource;
    sourceRef: SpeakingSourceRef;
    sessionId?: string;
    title: string;
    startedAt: string;
    endedAt: string;
    range: {
      firstMessageId: string;
      lastMessageId: string;
    };
    messages: Array<SpeakingHistoryMessage>;
  };
  result: SpeakingRecordedResult;
};

export type SpeakingReviewEvidence = {
  messageId: string;
  quote: string;
};

export type SpeakingReviewValidation = {
  valid: boolean;
  contentHash: string | null;
  errors: Array<SpeakingValidationIssue>;
  warnings: Array<SpeakingValidationIssue>;
};

export type SpeakingSavedReview = {
  sessionId: string;
  reviewId: string;
  status: "saved" | "alreadySaved";
  actualUseCount: number;
  recommendationCount: number;
};

export type SpeakingSessionCreate = {
  clientSessionId: string;
  title: string;
  startedAt: string;
  /**
   * 頁面確認的帳號；須與當前 session 相同，避免另一分頁切換帳號後誤寫
   */
  expectedUserId: string;
};

export type SpeakingSessionDetail = {
  session: SpeakingSessionRecord;
  review: SpeakingRecordedResult;
  legacySummaries: Array<SpeakingLegacySummaryInput>;
};

export type SpeakingSessionRecord = {
  id: string;
  clientSessionId: string;
  source: SpeakingHistorySource;
  title: string;
  startedAt: string;
  endedAt: string | null;
  createdAt: string;
  updatedAt: string;
  revision: number;
  messageCount: number;
  reviewed: boolean;
  summary: string | null;
};

export type SpeakingSourceRef = {
  system: string;
  conversationId: string;
  sessionKey: string;
};

export type SpeakingValidationIssue = {
  path: string;
  code: string;
  message: string;
};

export type _1Auth1Cli1Authorizations = unknown;

export type _1Auth1Cli1Authorizations1Id1Approve = unknown;

export type _1Auth1Cli1Authorizations1Id1Exchange = unknown;

export type _1Speaking1HistoryMigrations = unknown;

export type _1Speaking1PracticeContext = unknown;

export type _1Speaking1Reviews = unknown;

export type _1Speaking1Reviews1Validate = unknown;

export type _1Speaking1Sessions = unknown;

export type _1Speaking1Sessions1Id = unknown;

export type _1Speaking1Sessions1Id1Messages = unknown;

export type ListSpeakingSessionsData = {
  body?: never;
  path?: never;
  query?: {
    cursor?: string;
    limit?: number;
  };
  url: "/speaking/sessions";
};

export type ListSpeakingSessionsErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type ListSpeakingSessionsError =
  ListSpeakingSessionsErrors[keyof ListSpeakingSessionsErrors];

export type ListSpeakingSessionsResponses = {
  /**
   * 成功
   */
  200: {
    data: Array<SpeakingSessionRecord>;
    meta: SpeakingHistoryPageMeta;
  };
};

export type ListSpeakingSessionsResponse =
  ListSpeakingSessionsResponses[keyof ListSpeakingSessionsResponses];

export type CreateSpeakingSessionData = {
  body: SpeakingSessionCreate;
  path?: never;
  query?: never;
  url: "/speaking/sessions";
};

export type CreateSpeakingSessionErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type CreateSpeakingSessionError =
  CreateSpeakingSessionErrors[keyof CreateSpeakingSessionErrors];

export type CreateSpeakingSessionResponses = {
  /**
   * 成功
   */
  201: {
    data: SpeakingSessionRecord;
  };
};

export type CreateSpeakingSessionResponse =
  CreateSpeakingSessionResponses[keyof CreateSpeakingSessionResponses];

export type DeleteSpeakingSessionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/speaking/sessions/{id}";
};

export type DeleteSpeakingSessionErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type DeleteSpeakingSessionError =
  DeleteSpeakingSessionErrors[keyof DeleteSpeakingSessionErrors];

export type DeleteSpeakingSessionResponses = {
  /**
   * 成功
   */
  204: void;
};

export type DeleteSpeakingSessionResponse =
  DeleteSpeakingSessionResponses[keyof DeleteSpeakingSessionResponses];

export type GetSpeakingSessionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/speaking/sessions/{id}";
};

export type GetSpeakingSessionErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type GetSpeakingSessionError =
  GetSpeakingSessionErrors[keyof GetSpeakingSessionErrors];

export type GetSpeakingSessionResponses = {
  /**
   * 成功
   */
  200: {
    data: SpeakingSessionDetail;
  };
};

export type GetSpeakingSessionResponse =
  GetSpeakingSessionResponses[keyof GetSpeakingSessionResponses];

export type ListSpeakingMessagesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    cursor?: string;
    limit?: number;
  };
  url: "/speaking/sessions/{id}/messages";
};

export type ListSpeakingMessagesErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type ListSpeakingMessagesError =
  ListSpeakingMessagesErrors[keyof ListSpeakingMessagesErrors];

export type ListSpeakingMessagesResponses = {
  /**
   * 成功
   */
  200: {
    data: Array<SpeakingHistoryMessage>;
    meta: SpeakingHistoryPageMeta;
  };
};

export type ListSpeakingMessagesResponse =
  ListSpeakingMessagesResponses[keyof ListSpeakingMessagesResponses];

export type AppendSpeakingMessagesData = {
  body: SpeakingMessagesAppend;
  path: {
    id: string;
  };
  query?: never;
  url: "/speaking/sessions/{id}/messages";
};

export type AppendSpeakingMessagesErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type AppendSpeakingMessagesError =
  AppendSpeakingMessagesErrors[keyof AppendSpeakingMessagesErrors];

export type AppendSpeakingMessagesResponses = {
  /**
   * 成功
   */
  200: {
    data: SpeakingSessionRecord;
  };
};

export type AppendSpeakingMessagesResponse =
  AppendSpeakingMessagesResponses[keyof AppendSpeakingMessagesResponses];

export type GetSpeakingPracticeContextData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/speaking/practice-context";
};

export type GetSpeakingPracticeContextErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type GetSpeakingPracticeContextError =
  GetSpeakingPracticeContextErrors[keyof GetSpeakingPracticeContextErrors];

export type GetSpeakingPracticeContextResponses = {
  /**
   * 成功
   */
  200: {
    data: SpeakingPracticeContext;
  };
};

export type GetSpeakingPracticeContextResponse =
  GetSpeakingPracticeContextResponses[keyof GetSpeakingPracticeContextResponses];

export type ValidateSpeakingReviewData = {
  body: SpeakingReviewDraft;
  path?: never;
  query?: never;
  url: "/speaking/reviews/validate";
};

export type ValidateSpeakingReviewErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type ValidateSpeakingReviewError =
  ValidateSpeakingReviewErrors[keyof ValidateSpeakingReviewErrors];

export type ValidateSpeakingReviewResponses = {
  /**
   * 成功
   */
  200: {
    data: SpeakingReviewValidation;
  };
};

export type ValidateSpeakingReviewResponse =
  ValidateSpeakingReviewResponses[keyof ValidateSpeakingReviewResponses];

export type SaveSpeakingReviewData = {
  body: SpeakingReviewDraft;
  path?: never;
  query?: never;
  url: "/speaking/reviews";
};

export type SaveSpeakingReviewErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type SaveSpeakingReviewError =
  SaveSpeakingReviewErrors[keyof SaveSpeakingReviewErrors];

export type SaveSpeakingReviewResponses = {
  /**
   * 相同內容已保存，本次未重複計次
   */
  200: {
    data: SpeakingSavedReview;
  };
  /**
   * 成功
   */
  201: {
    data: SpeakingSavedReview;
  };
};

export type SaveSpeakingReviewResponse =
  SaveSpeakingReviewResponses[keyof SaveSpeakingReviewResponses];

export type MigrateSpeakingHistoryData = {
  body: SpeakingHistoryMigration;
  path?: never;
  query?: never;
  url: "/speaking/history-migrations";
};

export type MigrateSpeakingHistoryErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type MigrateSpeakingHistoryError =
  MigrateSpeakingHistoryErrors[keyof MigrateSpeakingHistoryErrors];

export type MigrateSpeakingHistoryResponses = {
  /**
   * 成功
   */
  200: {
    data: Array<SpeakingMigrationResult>;
  };
};

export type MigrateSpeakingHistoryResponse =
  MigrateSpeakingHistoryResponses[keyof MigrateSpeakingHistoryResponses];

export type CreateCliLoginAuthorizationData = {
  body: CliAuthorizationCreate;
  path?: never;
  query?: never;
  url: "/auth/cli/authorizations";
};

export type CreateCliLoginAuthorizationErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type CreateCliLoginAuthorizationError =
  CreateCliLoginAuthorizationErrors[keyof CreateCliLoginAuthorizationErrors];

export type CreateCliLoginAuthorizationResponses = {
  /**
   * 成功
   */
  201: {
    data: CliAuthorizationStarted;
  };
};

export type CreateCliLoginAuthorizationResponse =
  CreateCliLoginAuthorizationResponses[keyof CreateCliLoginAuthorizationResponses];

export type ApproveCliLoginAuthorizationData = {
  body: CliAuthorizationApprove;
  path: {
    id: string;
  };
  query?: never;
  url: "/auth/cli/authorizations/{id}/approve";
};

export type ApproveCliLoginAuthorizationErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 授權已過期
   */
  410: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type ApproveCliLoginAuthorizationError =
  ApproveCliLoginAuthorizationErrors[keyof ApproveCliLoginAuthorizationErrors];

export type ApproveCliLoginAuthorizationResponses = {
  /**
   * 成功
   */
  200: {
    data: CliAuthorizationStatus;
  };
};

export type ApproveCliLoginAuthorizationResponse =
  ApproveCliLoginAuthorizationResponses[keyof ApproveCliLoginAuthorizationResponses];

export type ExchangeCliLoginAuthorizationData = {
  body: CliAuthorizationExchange;
  path: {
    id: string;
  };
  query?: never;
  url: "/auth/cli/authorizations/{id}/exchange";
};

export type ExchangeCliLoginAuthorizationErrors = {
  /**
   * 格式錯誤
   */
  400: SpeakingHistoryError;
  /**
   * 未登入
   */
  401: SpeakingHistoryError;
  /**
   * 禁止存取
   */
  403: SpeakingHistoryError;
  /**
   * 找不到資源
   */
  404: SpeakingHistoryError;
  /**
   * 內容或版本衝突
   */
  409: SpeakingHistoryError;
  /**
   * 授權已過期
   */
  410: SpeakingHistoryError;
  /**
   * 資料超過限制
   */
  413: SpeakingHistoryError;
  /**
   * 驗證不符
   */
  422: SpeakingHistoryError;
  /**
   * 請求過於頻繁
   */
  429: SpeakingHistoryError;
};

export type ExchangeCliLoginAuthorizationError =
  ExchangeCliLoginAuthorizationErrors[keyof ExchangeCliLoginAuthorizationErrors];

export type ExchangeCliLoginAuthorizationResponses = {
  /**
   * 成功
   */
  200: {
    data: CliAuthorizationStatus;
  };
};

export type ExchangeCliLoginAuthorizationResponse =
  ExchangeCliLoginAuthorizationResponses[keyof ExchangeCliLoginAuthorizationResponses];

export type RegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * Email 已被使用
   */
  409: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
  /**
   * 註冊成功
   */
  201: UserResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type LoginErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 帳密錯誤
   */
  401: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * 登入成功
   */
  200: UserResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type LogoutErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * 登出成功
   */
  204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type InitiateGoogleOAuthData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * 是否記住登入狀態
     */
    rememberMe?: boolean;
  };
  url: "/auth/google";
};

export type HandleGoogleOAuthCallbackData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Google 授權碼
     */
    code: string;
    /**
     * 狀態參數（含 rememberMe 等資訊）
     */
    state?: string;
  };
  url: "/auth/google/callback";
};

export type HandleGoogleOAuthCallbackErrors = {
  /**
   * Google 授權失敗
   */
  401: ErrorResponse;
};

export type HandleGoogleOAuthCallbackError =
  HandleGoogleOAuthCallbackErrors[keyof HandleGoogleOAuthCallbackErrors];

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/me";
};

export type GetCurrentUserErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type GetCurrentUserError =
  GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
  /**
   * 成功
   */
  200: UserResponse;
};

export type GetCurrentUserResponse =
  GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListDecksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/decks";
};

export type ListDecksErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type ListDecksError = ListDecksErrors[keyof ListDecksErrors];

export type ListDecksResponses = {
  /**
   * 成功
   */
  200: DeckListResponse;
};

export type ListDecksResponse = ListDecksResponses[keyof ListDecksResponses];

export type CreateDeckData = {
  body: CreateDeckRequest;
  path?: never;
  query?: never;
  url: "/decks";
};

export type CreateDeckErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type CreateDeckError = CreateDeckErrors[keyof CreateDeckErrors];

export type CreateDeckResponses = {
  /**
   * 建立成功
   */
  201: DeckResponse;
};

export type CreateDeckResponse = CreateDeckResponses[keyof CreateDeckResponses];

export type DeleteDeckData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    id: string;
  };
  query?: never;
  url: "/decks/{id}";
};

export type DeleteDeckErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限刪除此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type DeleteDeckError = DeleteDeckErrors[keyof DeleteDeckErrors];

export type DeleteDeckResponses = {
  /**
   * 刪除成功
   */
  204: void;
};

export type DeleteDeckResponse = DeleteDeckResponses[keyof DeleteDeckResponses];

export type GetDeckData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    id: string;
  };
  query?: never;
  url: "/decks/{id}";
};

export type GetDeckErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type GetDeckError = GetDeckErrors[keyof GetDeckErrors];

export type GetDeckResponses = {
  /**
   * 成功
   */
  200: DeckDetailResponse;
};

export type GetDeckResponse = GetDeckResponses[keyof GetDeckResponses];

export type UpdateDeckData = {
  body: UpdateDeckRequest;
  path: {
    /**
     * 牌組 ID
     */
    id: string;
  };
  query?: never;
  url: "/decks/{id}";
};

export type UpdateDeckErrors = {
  /**
   * 輸入資料格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限修改此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type UpdateDeckError = UpdateDeckErrors[keyof UpdateDeckErrors];

export type UpdateDeckResponses = {
  /**
   * 更新成功
   */
  200: DeckResponse;
};

export type UpdateDeckResponse = UpdateDeckResponses[keyof UpdateDeckResponses];

export type ExportDeckData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    id: string;
  };
  query?: never;
  url: "/decks/{id}/export";
};

export type ExportDeckErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type ExportDeckError = ExportDeckErrors[keyof ExportDeckErrors];

export type ExportDeckResponses = {
  /**
   * 成功
   */
  200: DeckExportResponse;
};

export type ExportDeckResponse = ExportDeckResponses[keyof ExportDeckResponses];

export type ImportDeckData = {
  body: DeckExport;
  path?: never;
  query?: never;
  url: "/decks/import";
};

export type ImportDeckErrors = {
  /**
   * JSON 格式或版本不正確
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type ImportDeckError = ImportDeckErrors[keyof ImportDeckErrors];

export type ImportDeckResponses = {
  /**
   * 匯入成功
   */
  201: DeckImportResponse;
};

export type ImportDeckResponse = ImportDeckResponses[keyof ImportDeckResponses];

export type ListCardsData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
  };
  query?: never;
  url: "/decks/{deckId}/cards";
};

export type ListCardsErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type ListCardsError = ListCardsErrors[keyof ListCardsErrors];

export type ListCardsResponses = {
  /**
   * 成功
   */
  200: CardListResponse;
};

export type ListCardsResponse = ListCardsResponses[keyof ListCardsResponses];

export type CreateCardData = {
  body: CreateCardRequest;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
  };
  query?: never;
  url: "/decks/{deckId}/cards";
};

export type CreateCardErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type CreateCardError = CreateCardErrors[keyof CreateCardErrors];

export type CreateCardResponses = {
  /**
   * 建立成功
   */
  201: CardResponse;
};

export type CreateCardResponse = CreateCardResponses[keyof CreateCardResponses];

export type DeleteCardData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
    /**
     * 卡片 ID
     */
    cardId: string;
  };
  query?: never;
  url: "/decks/{deckId}/cards/{cardId}";
};

export type DeleteCardErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 卡片不存在
   */
  404: ErrorResponse;
};

export type DeleteCardError = DeleteCardErrors[keyof DeleteCardErrors];

export type DeleteCardResponses = {
  /**
   * 刪除成功
   */
  204: void;
};

export type DeleteCardResponse = DeleteCardResponses[keyof DeleteCardResponses];

export type GetCardData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
    /**
     * 卡片 ID
     */
    cardId: string;
  };
  query?: never;
  url: "/decks/{deckId}/cards/{cardId}";
};

export type GetCardErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 卡片不存在
   */
  404: ErrorResponse;
};

export type GetCardError = GetCardErrors[keyof GetCardErrors];

export type GetCardResponses = {
  /**
   * 成功
   */
  200: CardResponse;
};

export type GetCardResponse = GetCardResponses[keyof GetCardResponses];

export type UpdateCardData = {
  body: UpdateCardRequest;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
    /**
     * 卡片 ID
     */
    cardId: string;
  };
  query?: never;
  url: "/decks/{deckId}/cards/{cardId}";
};

export type UpdateCardErrors = {
  /**
   * 輸入資料格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 卡片不存在
   */
  404: ErrorResponse;
};

export type UpdateCardError = UpdateCardErrors[keyof UpdateCardErrors];

export type UpdateCardResponses = {
  /**
   * 更新成功
   */
  200: CardResponse;
};

export type UpdateCardResponse = UpdateCardResponses[keyof UpdateCardResponses];

export type ImportCardsData = {
  body: ImportCardsRequest;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
  };
  query?: never;
  url: "/decks/{deckId}/cards/import";
};

export type ImportCardsErrors = {
  /**
   * 輸入資料格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type ImportCardsError = ImportCardsErrors[keyof ImportCardsErrors];

export type ImportCardsResponses = {
  /**
   * 匯入完成（可能部分成功）
   */
  201: ImportCardsResponse;
};

export type ImportCardsResponse2 =
  ImportCardsResponses[keyof ImportCardsResponses];

export type ListTargetVocabularyData = {
  body?: never;
  path?: never;
  query?: {
    status?: TargetVocabularyStatus;
    q?: string;
  };
  url: "/target-vocabulary";
};

export type ListTargetVocabularyErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type ListTargetVocabularyError =
  ListTargetVocabularyErrors[keyof ListTargetVocabularyErrors];

export type ListTargetVocabularyResponses = {
  /**
   * 成功
   */
  200: TargetVocabularyListResponse;
};

export type ListTargetVocabularyResponse =
  ListTargetVocabularyResponses[keyof ListTargetVocabularyResponses];

export type ImportTargetVocabularyData = {
  body: ImportTargetVocabularyRequest;
  path?: never;
  query?: never;
  url: "/target-vocabulary/import";
};

export type ImportTargetVocabularyErrors = {
  /**
   * 輸入資料格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type ImportTargetVocabularyError =
  ImportTargetVocabularyErrors[keyof ImportTargetVocabularyErrors];

export type ImportTargetVocabularyResponses = {
  /**
   * 匯入完成
   */
  201: ImportTargetVocabularyResponse;
};

export type ImportTargetVocabularyResponse2 =
  ImportTargetVocabularyResponses[keyof ImportTargetVocabularyResponses];

export type AddTargetVocabularyToDeckData = {
  body: AddTargetVocabularyToDeckRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/target-vocabulary/{id}/add-to-deck";
};

export type AddTargetVocabularyToDeckErrors = {
  /**
   * 輸入資料格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到目標單字或牌組
   */
  404: ErrorResponse;
  /**
   * 目標單字尚未在 Speaking 實際使用
   */
  422: ErrorResponse;
};

export type AddTargetVocabularyToDeckError =
  AddTargetVocabularyToDeckErrors[keyof AddTargetVocabularyToDeckErrors];

export type AddTargetVocabularyToDeckResponses = {
  /**
   * 已建立或連結單字卡
   */
  201: AddTargetVocabularyToDeckResponse;
};

export type AddTargetVocabularyToDeckResponse2 =
  AddTargetVocabularyToDeckResponses[keyof AddTargetVocabularyToDeckResponses];

export type RejectTargetVocabularyUseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/target-vocabulary/{id}/reject-use";
};

export type RejectTargetVocabularyUseErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到目標單字
   */
  404: ErrorResponse;
  /**
   * 目標單字不在可撤銷的已使用狀態
   */
  422: ErrorResponse;
};

export type RejectTargetVocabularyUseError =
  RejectTargetVocabularyUseErrors[keyof RejectTargetVocabularyUseErrors];

export type RejectTargetVocabularyUseResponses = {
  /**
   * 已撤銷使用判定
   */
  200: RejectTargetVocabularyUseResponse;
};

export type RejectTargetVocabularyUseResponse2 =
  RejectTargetVocabularyUseResponses[keyof RejectTargetVocabularyUseResponses];

export type ListCollectionItemsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * 收藏項目類型
     */
    kind?: CollectionItemKind;
    /**
     * 搜尋關鍵字
     */
    q?: string;
    /**
     * 下一頁 cursor
     */
    cursor?: string;
    /**
     * 每頁數量
     */
    limit?: number;
  };
  url: "/collections";
};

export type ListCollectionItemsErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
};

export type ListCollectionItemsError =
  ListCollectionItemsErrors[keyof ListCollectionItemsErrors];

export type ListCollectionItemsResponses = {
  /**
   * 成功
   */
  200: CollectionItemListResponse;
};

export type ListCollectionItemsResponse =
  ListCollectionItemsResponses[keyof ListCollectionItemsResponses];

export type CreateCollectionItemData = {
  body: CreateCollectionItemRequest;
  path?: never;
  query?: never;
  url: "/collections";
};

export type CreateCollectionItemErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限連結指定卡片或非白名單使用者
   */
  403: ErrorResponse;
};

export type CreateCollectionItemError =
  CreateCollectionItemErrors[keyof CreateCollectionItemErrors];

export type CreateCollectionItemResponses = {
  /**
   * 建立成功
   */
  201: CollectionItemResponse;
};

export type CreateCollectionItemResponse =
  CreateCollectionItemResponses[keyof CreateCollectionItemResponses];

export type DeleteCollectionItemData = {
  body?: never;
  path: {
    /**
     * 收藏項目 ID
     */
    id: string;
  };
  query?: never;
  url: "/collections/{id}";
};

export type DeleteCollectionItemErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * 收藏項目不存在
   */
  404: ErrorResponse;
};

export type DeleteCollectionItemError =
  DeleteCollectionItemErrors[keyof DeleteCollectionItemErrors];

export type DeleteCollectionItemResponses = {
  /**
   * 刪除成功
   */
  204: void;
};

export type DeleteCollectionItemResponse =
  DeleteCollectionItemResponses[keyof DeleteCollectionItemResponses];

export type GetCollectionItemData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/collections/{id}";
};

export type GetCollectionItemErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 收藏項目不存在
   */
  404: ErrorResponse;
};

export type GetCollectionItemError =
  GetCollectionItemErrors[keyof GetCollectionItemErrors];

export type GetCollectionItemResponses = {
  /**
   * 成功
   */
  200: CollectionItemResponse;
};

export type GetCollectionItemResponse =
  GetCollectionItemResponses[keyof GetCollectionItemResponses];

export type UpdateCollectionItemData = {
  body: UpdateCollectionItemRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/collections/{id}";
};

export type UpdateCollectionItemErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 收藏項目不存在
   */
  404: ErrorResponse;
};

export type UpdateCollectionItemError =
  UpdateCollectionItemErrors[keyof UpdateCollectionItemErrors];

export type UpdateCollectionItemResponses = {
  /**
   * 更新成功
   */
  200: CollectionItemResponse;
};

export type UpdateCollectionItemResponse =
  UpdateCollectionItemResponses[keyof UpdateCollectionItemResponses];

export type CreateCollectionChatSessionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/collections/chat-sessions";
};

export type CreateCollectionChatSessionErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
};

export type CreateCollectionChatSessionError =
  CreateCollectionChatSessionErrors[keyof CreateCollectionChatSessionErrors];

export type CreateCollectionChatSessionResponses = {
  /**
   * 建立成功
   */
  201: CollectionChatSessionResponse;
};

export type CreateCollectionChatSessionResponse =
  CreateCollectionChatSessionResponses[keyof CreateCollectionChatSessionResponses];

export type ListCollectionChatMessagesData = {
  body?: never;
  path: {
    /**
     * 聊天 session ID
     */
    sessionId: string;
  };
  query?: never;
  url: "/collections/chat-sessions/{sessionId}/messages";
};

export type ListCollectionChatMessagesErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取 session 或非白名單使用者
   */
  403: ErrorResponse;
  /**
   * 找不到聊天 session
   */
  404: ErrorResponse;
};

export type ListCollectionChatMessagesError =
  ListCollectionChatMessagesErrors[keyof ListCollectionChatMessagesErrors];

export type ListCollectionChatMessagesResponses = {
  /**
   * 成功
   */
  200: CollectionChatMessageListResponse;
};

export type ListCollectionChatMessagesResponse =
  ListCollectionChatMessagesResponses[keyof ListCollectionChatMessagesResponses];

export type CreateCollectionChatMessageData = {
  body: CreateCollectionChatMessageRequest;
  path: {
    /**
     * 聊天 session ID
     */
    sessionId: string;
  };
  query?: never;
  url: "/collections/chat-sessions/{sessionId}/messages";
};

export type CreateCollectionChatMessageErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取 session 或非白名單使用者
   */
  403: ErrorResponse;
  /**
   * 聊天 session 不存在
   */
  404: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type CreateCollectionChatMessageError =
  CreateCollectionChatMessageErrors[keyof CreateCollectionChatMessageErrors];

export type CreateCollectionChatMessageResponses = {
  /**
   * 成功
   */
  200: CollectionChatMessageResponse;
};

export type CreateCollectionChatMessageResponse =
  CreateCollectionChatMessageResponses[keyof CreateCollectionChatMessageResponses];

export type ListTopicConversationsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Base64 編碼的下一頁 cursor
     */
    cursor?: string;
    /**
     * 每頁場次數量
     */
    limit?: number;
  };
  url: "/topic-conversations";
};

export type ListTopicConversationsErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type ListTopicConversationsError =
  ListTopicConversationsErrors[keyof ListTopicConversationsErrors];

export type ListTopicConversationsResponses = {
  /**
   * 成功
   */
  200: TopicConversationSessionListResponse;
};

export type ListTopicConversationsResponse =
  ListTopicConversationsResponses[keyof ListTopicConversationsResponses];

export type CreateTopicConversationData = {
  body: TopicConversationDraft;
  path?: never;
  query?: never;
  url: "/topic-conversations";
};

export type CreateTopicConversationErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 暫時無法產生不同的新主題
   */
  409: ErrorResponse;
  /**
   * AI 服務錯誤或無法產生不重複主題
   */
  500: ErrorResponse;
};

export type CreateTopicConversationError =
  CreateTopicConversationErrors[keyof CreateTopicConversationErrors];

export type CreateTopicConversationResponses = {
  /**
   * 建立成功
   */
  201: TopicConversationSessionDetailResponse;
};

export type CreateTopicConversationResponse =
  CreateTopicConversationResponses[keyof CreateTopicConversationResponses];

export type CreateTopicConversationDraftData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/topic-conversations/draft";
};

export type CreateTopicConversationDraftErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type CreateTopicConversationDraftError =
  CreateTopicConversationDraftErrors[keyof CreateTopicConversationDraftErrors];

export type CreateTopicConversationDraftResponses = {
  /**
   * 草稿產生成功
   */
  200: {
    data: TopicConversationDraft;
  };
};

export type CreateTopicConversationDraftResponse =
  CreateTopicConversationDraftResponses[keyof CreateTopicConversationDraftResponses];

export type CreateTopicConversationDraftHintData = {
  body: TopicConversationDraft;
  path?: never;
  query?: never;
  url: "/topic-conversations/draft/hint";
};

export type CreateTopicConversationDraftHintErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
};

export type CreateTopicConversationDraftHintError =
  CreateTopicConversationDraftHintErrors[keyof CreateTopicConversationDraftHintErrors];

export type CreateTopicConversationDraftHintResponses = {
  /**
   * 成功
   */
  200: TopicConversationHintResponse;
};

export type CreateTopicConversationDraftHintResponse =
  CreateTopicConversationDraftHintResponses[keyof CreateTopicConversationDraftHintResponses];

export type DeleteTopicConversationData = {
  body?: never;
  path: {
    /**
     * 主題對話場次 ID
     */
    id: string;
  };
  query?: never;
  url: "/topic-conversations/{id}";
};

export type DeleteTopicConversationErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到主題對話場次
   */
  404: ErrorResponse;
};

export type DeleteTopicConversationError =
  DeleteTopicConversationErrors[keyof DeleteTopicConversationErrors];

export type DeleteTopicConversationResponses = {
  /**
   * 刪除成功
   */
  204: void;
};

export type DeleteTopicConversationResponse =
  DeleteTopicConversationResponses[keyof DeleteTopicConversationResponses];

export type GetTopicConversationData = {
  body?: never;
  path: {
    /**
     * 主題對話場次 ID
     */
    id: string;
  };
  query?: never;
  url: "/topic-conversations/{id}";
};

export type GetTopicConversationErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到主題對話場次
   */
  404: ErrorResponse;
};

export type GetTopicConversationError =
  GetTopicConversationErrors[keyof GetTopicConversationErrors];

export type GetTopicConversationResponses = {
  /**
   * 成功
   */
  200: TopicConversationSessionDetailResponse;
};

export type GetTopicConversationResponse =
  GetTopicConversationResponses[keyof GetTopicConversationResponses];

export type CreateTopicConversationMessageData = {
  body: CreateTopicConversationMessageRequest;
  path: {
    /**
     * 主題對話場次 ID
     */
    id: string;
  };
  query?: never;
  url: "/topic-conversations/{id}/messages";
};

export type CreateTopicConversationMessageErrors = {
  /**
   * 訊息為空白或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到主題對話場次
   */
  404: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type CreateTopicConversationMessageError =
  CreateTopicConversationMessageErrors[keyof CreateTopicConversationMessageErrors];

export type CreateTopicConversationMessageResponses = {
  /**
   * 成功
   */
  200: TopicConversationMessageResponse;
};

export type CreateTopicConversationMessageResponse =
  CreateTopicConversationMessageResponses[keyof CreateTopicConversationMessageResponses];

export type StreamTopicConversationMessageData = {
  body: CreateTopicConversationMessageRequest;
  path: {
    /**
     * 主題對話場次 ID
     */
    id: string;
  };
  query?: never;
  url: "/topic-conversations/{id}/messages/stream";
};

export type StreamTopicConversationMessageErrors = {
  /**
   * 訊息為空白或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到主題對話場次
   */
  404: ErrorResponse;
};

export type StreamTopicConversationMessageError =
  StreamTopicConversationMessageErrors[keyof StreamTopicConversationMessageErrors];

export type StreamTopicConversationMessageResponses = {
  /**
   * SSE 串流，依序包含 assistant_delta、result 與 done 事件
   */
  200: string;
};

export type StreamTopicConversationMessageResponse =
  StreamTopicConversationMessageResponses[keyof StreamTopicConversationMessageResponses];

export type CreateTopicConversationHintData = {
  body?: never;
  path: {
    /**
     * 主題對話場次 ID
     */
    id: string;
  };
  query?: never;
  url: "/topic-conversations/{id}/hint";
};

export type CreateTopicConversationHintErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到主題對話場次
   */
  404: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type CreateTopicConversationHintError =
  CreateTopicConversationHintErrors[keyof CreateTopicConversationHintErrors];

export type CreateTopicConversationHintResponses = {
  /**
   * 成功
   */
  200: TopicConversationHintResponse;
};

export type CreateTopicConversationHintResponse =
  CreateTopicConversationHintResponses[keyof CreateTopicConversationHintResponses];

export type ReplayTopicConversationData = {
  body?: never;
  path: {
    /**
     * 原始主題對話場次 ID
     */
    id: string;
  };
  query?: never;
  url: "/topic-conversations/{id}/replay";
};

export type ReplayTopicConversationErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 找不到原始主題對話場次
   */
  404: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type ReplayTopicConversationError =
  ReplayTopicConversationErrors[keyof ReplayTopicConversationErrors];

export type ReplayTopicConversationResponses = {
  /**
   * 建立成功
   */
  201: TopicConversationSessionDetailResponse;
};

export type ReplayTopicConversationResponse =
  ReplayTopicConversationResponses[keyof ReplayTopicConversationResponses];

export type GenerateCardContentData = {
  body: GenerateCardContentRequest;
  path?: never;
  query?: never;
  url: "/ai/generate-card-content";
};

export type GenerateCardContentErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type GenerateCardContentError =
  GenerateCardContentErrors[keyof GenerateCardContentErrors];

export type GenerateCardContentResponses = {
  /**
   * 生成成功
   */
  200: GenerateCardContentResponse;
};

export type GenerateCardContentResponse2 =
  GenerateCardContentResponses[keyof GenerateCardContentResponses];

export type GetStudyCardsData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
  };
  query?: never;
  url: "/decks/{deckId}/study/cards";
};

export type GetStudyCardsErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type GetStudyCardsError = GetStudyCardsErrors[keyof GetStudyCardsErrors];

export type GetStudyCardsResponses = {
  /**
   * 成功
   */
  200: StudyCardsResponse;
};

export type GetStudyCardsResponse =
  GetStudyCardsResponses[keyof GetStudyCardsResponses];

export type SubmitReviewData = {
  body: SubmitReviewRequest;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
  };
  query?: never;
  url: "/decks/{deckId}/study/review";
};

export type SubmitReviewErrors = {
  /**
   * 輸入資料格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組或卡片不存在
   */
  404: ErrorResponse;
};

export type SubmitReviewError = SubmitReviewErrors[keyof SubmitReviewErrors];

export type SubmitReviewResponses = {
  /**
   * 評分成功
   */
  200: ReviewResultResponse;
};

export type SubmitReviewResponse =
  SubmitReviewResponses[keyof SubmitReviewResponses];

export type GenerateRelatedExampleData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
    /**
     * 卡片 ID
     */
    cardId: string;
  };
  query?: never;
  url: "/decks/{deckId}/study/cards/{cardId}/related-example";
};

export type GenerateRelatedExampleErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組或卡片不存在
   */
  404: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type GenerateRelatedExampleError =
  GenerateRelatedExampleErrors[keyof GenerateRelatedExampleErrors];

export type GenerateRelatedExampleResponses = {
  /**
   * 產生成功
   */
  200: RelatedExampleResponse;
};

export type GenerateRelatedExampleResponse =
  GenerateRelatedExampleResponses[keyof GenerateRelatedExampleResponses];

export type GetStudySummaryData = {
  body?: never;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
  };
  query?: never;
  url: "/decks/{deckId}/study/summary";
};

export type GetStudySummaryErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
};

export type GetStudySummaryError =
  GetStudySummaryErrors[keyof GetStudySummaryErrors];

export type GetStudySummaryResponses = {
  /**
   * 成功
   */
  200: StudySummaryResponse;
};

export type GetStudySummaryResponse =
  GetStudySummaryResponses[keyof GetStudySummaryResponses];

export type SetDailyOverrideData = {
  body: SetDailyOverrideRequest;
  path: {
    /**
     * 牌組 ID
     */
    deckId: string;
  };
  query?: never;
  url: "/decks/{deckId}/daily-override";
};

export type SetDailyOverrideErrors = {
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 無權限存取此牌組
   */
  403: ErrorResponse;
  /**
   * 牌組不存在
   */
  404: ErrorResponse;
  /**
   * 覆寫值低於預設值
   */
  422: ErrorResponse;
};

export type SetDailyOverrideError =
  SetDailyOverrideErrors[keyof SetDailyOverrideErrors];

export type SetDailyOverrideResponses = {
  /**
   * 覆寫設定成功
   */
  200: SetDailyOverrideResponse;
};

export type SetDailyOverrideResponse2 =
  SetDailyOverrideResponses[keyof SetDailyOverrideResponses];

export type SynthesizeSpeechData = {
  body: SynthesizeSpeechRequest;
  path?: never;
  query?: never;
  url: "/tts/synthesize";
};

export type SynthesizeSpeechErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * TTS 服務錯誤
   */
  500: ErrorResponse;
};

export type SynthesizeSpeechError =
  SynthesizeSpeechErrors[keyof SynthesizeSpeechErrors];

export type SynthesizeSpeechResponses = {
  /**
   * MP3 音訊資料
   */
  200: Blob | File;
};

export type SynthesizeSpeechResponse =
  SynthesizeSpeechResponses[keyof SynthesizeSpeechResponses];

export type SynthesizeWordData = {
  body: SynthesizeWordRequest;
  path?: never;
  query?: never;
  url: "/tts/word";
};

export type SynthesizeWordErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * TTS 服務錯誤
   */
  500: ErrorResponse;
};

export type SynthesizeWordError =
  SynthesizeWordErrors[keyof SynthesizeWordErrors];

export type SynthesizeWordResponses = {
  /**
   * MP3 音訊資料
   */
  200: Blob | File;
};

export type SynthesizeWordResponse =
  SynthesizeWordResponses[keyof SynthesizeWordResponses];

export type CreateSpeakingReplyData = {
  body: SpeakingChatRequest;
  path?: never;
  query?: never;
  url: "/speaking/chat";
};

export type CreateSpeakingReplyErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type CreateSpeakingReplyError =
  CreateSpeakingReplyErrors[keyof CreateSpeakingReplyErrors];

export type CreateSpeakingReplyResponses = {
  /**
   * 成功
   */
  200: SpeakingChatResponse;
};

export type CreateSpeakingReplyResponse =
  CreateSpeakingReplyResponses[keyof CreateSpeakingReplyResponses];

export type CreateSpeakingAudioReplyData = {
  body: SpeakingAudioChatMultipartRequest;
  path?: never;
  query?: never;
  url: "/speaking/chat/audio";
};

export type CreateSpeakingAudioReplyErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type CreateSpeakingAudioReplyError =
  CreateSpeakingAudioReplyErrors[keyof CreateSpeakingAudioReplyErrors];

export type CreateSpeakingAudioReplyResponses = {
  /**
   * 成功
   */
  200: SpeakingAudioChatResponse;
};

export type CreateSpeakingAudioReplyResponse =
  CreateSpeakingAudioReplyResponses[keyof CreateSpeakingAudioReplyResponses];

export type SummarizeSpeakingConversationData = {
  body: SpeakingSummarizeRequest;
  path?: never;
  query?: never;
  url: "/speaking/summarize";
};

export type SummarizeSpeakingConversationErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type SummarizeSpeakingConversationError =
  SummarizeSpeakingConversationErrors[keyof SummarizeSpeakingConversationErrors];

export type SummarizeSpeakingConversationResponses = {
  /**
   * 成功
   */
  200: SpeakingSummarizeResponse;
};

export type SummarizeSpeakingConversationResponse =
  SummarizeSpeakingConversationResponses[keyof SummarizeSpeakingConversationResponses];

export type TranslateSpeakingTextData = {
  body: SpeakingTranslateRequest;
  path?: never;
  query?: never;
  url: "/speaking/translate";
};

export type TranslateSpeakingTextErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type TranslateSpeakingTextError =
  TranslateSpeakingTextErrors[keyof TranslateSpeakingTextErrors];

export type TranslateSpeakingTextResponses = {
  /**
   * 成功
   */
  200: SpeakingTranslateResponse;
};

export type TranslateSpeakingTextResponse =
  TranslateSpeakingTextResponses[keyof TranslateSpeakingTextResponses];

export type ChatSpeakingAssistantData = {
  body: SpeakingAssistantChatRequest;
  path?: never;
  query?: never;
  url: "/speaking/assistant/chat";
};

export type ChatSpeakingAssistantErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type ChatSpeakingAssistantError =
  ChatSpeakingAssistantErrors[keyof ChatSpeakingAssistantErrors];

export type ChatSpeakingAssistantResponses = {
  /**
   * 成功
   */
  200: SpeakingAssistantChatResponse;
};

export type ChatSpeakingAssistantResponse =
  ChatSpeakingAssistantResponses[keyof ChatSpeakingAssistantResponses];

export type StreamSpeakingAssistantData = {
  body: SpeakingAssistantChatRequest;
  path?: never;
  query?: never;
  url: "/speaking/assistant/chat/stream";
};

export type StreamSpeakingAssistantErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type StreamSpeakingAssistantError =
  StreamSpeakingAssistantErrors[keyof StreamSpeakingAssistantErrors];

export type StreamSpeakingAssistantResponses = {
  /**
   * SSE 串流回應（assistant_delta、tool_call、tool_result、result、done）
   */
  200: string;
};

export type StreamSpeakingAssistantResponse =
  StreamSpeakingAssistantResponses[keyof StreamSpeakingAssistantResponses];

export type PreviewSpeakingVoiceData = {
  body?: SpeakingVoicePreviewRequest;
  path?: never;
  query?: never;
  url: "/speaking/voice-preview";
};

export type PreviewSpeakingVoiceErrors = {
  /**
   * 輸入資料不完整或格式錯誤
   */
  400: ErrorResponse;
  /**
   * 未授權
   */
  401: ErrorResponse;
  /**
   * 非白名單使用者
   */
  403: ErrorResponse;
  /**
   * AI 服務錯誤
   */
  500: ErrorResponse;
};

export type PreviewSpeakingVoiceError =
  PreviewSpeakingVoiceErrors[keyof PreviewSpeakingVoiceErrors];

export type PreviewSpeakingVoiceResponses = {
  /**
   * 成功
   */
  200: SpeakingVoicePreviewResponse;
};

export type PreviewSpeakingVoiceResponse =
  PreviewSpeakingVoiceResponses[keyof PreviewSpeakingVoiceResponses];
